### ISSUE TITLE
Game crashed when donating item in the museum

### ISSUE THREAD

**Issue by Neele03** [SkyblockerMod/Skyblocker#1083]
### Minecraft Version

1.21.0/1.21.1

### Skyblocker Version

skyblocker-1.21.0+1.21

### Reproduction Steps

Go to the museum and right click the NPC. Then click on any category and donate an item. Once the confirm button appears confirm the donation and then it crashes.

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-12-19 18:22:28
Description: mouseClicked event handler

java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectOpenHashSet.add(Object)" because the return value of "de.hysky.skyblocker.skyblock.item.MuseumItemCache$ProfileMuseumData.collectedItemIds()" is null
	at de.hysky.skyblocker.skyblock.item.MuseumItemCache.handleClick(MuseumItemCache.java:118)
	at net.minecraft.class_465.handler$cga000$skyblocker$onSlotClick(class_465.java:1461)
	at net.minecraft.class_465.method_2383(class_465.java:557)
	at net.minecraft.class_465.method_25402(class_465.java:349)
	at net.minecraft.class_312.method_1611(class_312.java:107)
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:107)
	at net.minecraft.class_312.method_22686(class_312.java:196)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:196)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168)
	at net.minecraft.class_1041.method_15998(class_1041.java:303)
	at net.minecraft.class_310.method_1523(class_310.java:1307)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

### Additional context

It was tested on two independent PCs. Both PCs run Windows 11 and use Microsofts jdk-21.0.5.11.

**Comment by kevinthegreat1** [comment]
Fixed in 1.21.1+1.21, please update.
