### ISSUE TITLE
Constant crash with better auction house

### ISSUE THREAD

**Issue by 22098-22098** [SkyblockerMod/Skyblocker#1107]
### Minecraft Version

1.21.0/1.21.1

### Skyblocker Version

skyblocker-1.20.2+1.20.4

### Reproduction Steps

trying to do anything in the ah provides this error

`[21:11:06] [Render thread/ERROR]: Error executing task on Client
net.minecraft.class_148: Main thread packet handler
	at net.minecraft.class_2600.method_11072(class_2600.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1283) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.9.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_7842.method_25355(net.minecraft.class_2561)" because "this.infoTextWidget" is null
	at de.hysky.skyblocker.skyblock.auction.AuctionViewScreen.changeState(AuctionViewScreen.java:98) ~[skyblocker-1.20.2+1.20.4.jar:?]
	at de.hysky.skyblocker.skyblock.auction.AuctionViewScreen.onSlotChange(AuctionViewScreen.java:208) ~[skyblocker-1.20.2+1.20.4.jar:?]
	at de.hysky.skyblocker.skyblock.auction.AuctionViewScreen.onSlotChange(AuctionViewScreen.java:30) ~[skyblocker-1.20.2+1.20.4.jar:?]
	at de.hysky.skyblocker.utils.render.gui.AbstractCustomHypixelGUI.method_7635(AbstractCustomHypixelGUI.java:48) ~[skyblocker-1.20.2+1.20.4.jar:?]
	at net.minecraft.class_1703.method_34246(class_1703.java:219) ~[client-intermediary.jar:?]
	at net.minecraft.class_1703.method_7623(class_1703.java:176) ~[client-intermediary.jar:?]
	at net.minecraft.class_1703.method_7596(class_1703.java:139) ~[client-intermediary.jar:?]
	at de.hysky.skyblocker.utils.render.gui.AbstractCustomHypixelGUI.<init>(AbstractCustomHypixelGUI.java:18) ~[skyblocker-1.20.2+1.20.4.jar:?]
	at de.hysky.skyblocker.skyblock.auction.AuctionViewScreen.<init>(AuctionViewScreen.java:50) ~[skyblocker-1.20.2+1.20.4.jar:?]
	at net.minecraft.class_3929$class_3930.handler$dap000$skyblocker$open(class_3929.java:568) ~[client-intermediary.jar:?]
	at net.minecraft.class_3929$class_3930.method_17543(class_3929.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_3929.method_17541(class_3929.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_17587(class_634.java:1182) ~[client-intermediary.jar:?]
	at net.minecraft.class_3944.method_17591(class_3944.java:37) ~[client-intermediary.jar:?]
	at net.minecraft.class_3944.method_11054(class_3944.java:11) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[client-intermediary.jar:?]
	... 13 more
[21:11:07] [Render thread/ERROR]: Error executing task on Client
net.minecraft.class_148: Main thread packet handler
	at net.minecraft.class_2600.method_11072(class_2600.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1283) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.9.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_7842.method_25355(net.minecraft.class_2561)" because "this.priceWidget" is null
	at de.hysky.skyblocker.skyblock.auction.AuctionViewScreen.getPriceFromTooltip(AuctionViewScreen.java:272) ~[skyblocker-1.20.2+1.20.4.jar:?]
	at de.hysky.skyblocker.skyblock.auction.AuctionViewScreen.onSlotChange(AuctionViewScreen.java:209) ~[skyblocker-1.20.2+1.20.4.jar:?]
	at de.hysky.skyblocker.skyblock.auction.AuctionViewScreen.onSlotChange(AuctionViewScreen.java:30) ~[skyblocker-1.20.2+1.20.4.jar:?]
	at de.hysky.skyblocker.utils.render.gui.AbstractCustomHypixelGUI.method_7635(AbstractCustomHypixelGUI.java:48) ~[skyblocker-1.20.2+1.20.4.jar:?]
	at net.minecraft.class_1703.method_34246(class_1703.java:219) ~[client-intermediary.jar:?]
	at net.minecraft.class_1703.method_7623(class_1703.java:176) ~[client-intermediary.jar:?]
	at net.minecraft.class_1703.method_7609(class_1703.java:589) ~[client-intermediary.jar:?]
	at de.hysky.skyblocker.skyblock.auction.AuctionHouseScreenHandler.method_7619(AuctionHouseScreenHandler.java:56) ~[skyblocker-1.20.2+1.20.4.jar:?]
	at net.minecraft.class_634.method_11109(class_634.java:1217) ~[client-intermediary.jar:?]
	at net.minecraft.class_2653.method_11451(class_2653.java:41) ~[client-intermediary.jar:?]
	at net.minecraft.class_2653.method_11054(class_2653.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[client-intermediary.jar:?]
	... 13 more`

### Additional context

i know this is a older version of minecraft (1.20.4) but a lot of other mods arnt one 1.21 yet so i would prefer to stay on this version

**Comment by RimeOrReason** [comment]
Looks like it was fixed by https://github.com/SkyblockerMod/Skyblocker/commit/aa246613ad1f44f02c1aaf80b9e779a998145a94#diff-539e8a5830eba79fcc57a16b4ed242908444aa31c7613fc9fededfcdd70fcd72L192-R207

**Comment by Emirlol** [comment]
Seems like it was fixed by https://github.com/SkyblockerMod/Skyblocker/commit/aa246613ad1f44f02c1aaf80b9e779a998145a94#diff-539e8a5830eba79fcc57a16b4ed242908444aa31c7613fc9fededfcdd70fcd72L192-R207

**Comment by Emirlol** [comment]
Most of the popular mods have been updated for 1.21. They might not have been updated for 1.21.3 or 1.21.4 but most of them should at least have a version for 1.21 or 1.21.1. I'd recommend updating them, but if you still don't want to update, you could at least update to [1.20.6](https://modrinth.com/mod/skyblocker-liap/version/v1.21.2+1.20.6) if you want to benefit from this fix.
