### ISSUE TITLE
Failed to download lowest BIN prices

### ISSUE THREAD

**Issue by Detlas-Legacy** [SkyblockerMod/Skyblocker#117]
Hi, me again.

[ForkJoinPool.commonPool-worker-3/WARN]: [Skyblocker] Failed to download lowest BIN prices!
java.io.FileNotFoundException: https://skytils.gg/api/auctions/lowestbins
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
	at java.net.URL.openStream(URL.java:1161) ~[?:?]
	at me.xmrvizzy.skyblocker.skyblock.item.PriceInfoTooltip.downloadLowestPrices(PriceInfoTooltip.java:357) ~[skyblocker-1.8.2+1.19.2.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

**Comment by Julienraptor01** [comment]
> Hi, me again.
> 
> [ForkJoinPool.commonPool-worker-3/WARN]: [Skyblocker] Failed to download lowest BIN prices!
> java.io.FileNotFoundException: https://skytils.gg/api/auctions/lowestbins
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993) ~[?:?]
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
> 	at java.net.URL.openStream(URL.java:1161) ~[?:?]
> 	at me.xmrvizzy.skyblocker.skyblock.item.PriceInfoTooltip.downloadLowestPrices(PriceInfoTooltip.java:357) ~[skyblocker-1.8.2+1.19.2.jar:?]
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
> 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
> 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

Skytils API is temporarily down, wait for it to go back up and it'll diseappear and actualize correctly

**Comment by Julienraptor01** [comment]
solved by #119 and should be closed
