### ISSUE TITLE
Incompatible Mod Set (v1.20.1)

### ISSUE THREAD

**Issue by Prabh-Saini** [SkyblockerMod/Skyblocker#181]
Skyblocker Version: The latest release (downloaded, didn't compile myself). And this is my first time using Skyblocker.
Minecraft Version: 1.20.1

Error occurs while loading up Minecraft. The useful error seems to be:
> Mod 'Skyblocker' (skyblocker) 1.10.0+1.19.4 requires any version between 1.19.4 (inclusive) and 1.20- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!

Which would suggest that it's a minor issue with configuration, because it does say that it supports Minecraft 1.20 and above. (I may be mistaken and it was your intention to only supported 1.20 not 1.20.x)
```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Skyblocker' (skyblocker) 1.10.0+1.19.4 with any version that is compatible with:
		 - minecraft 1.20.1
Unmet dependency listing:
	 - Mod 'Skyblocker' (skyblocker) 1.10.0+1.19.4 requires any version between 1.19.4 (inclusive) and 1.20- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by AzureAaron** [comment]
You're trying to use a version of skyblocker made for 1.19.4 on 1.20.1, for a version compatible with 1.20.1 you can download a beta from modrinth: https://modrinth.com/mod/skyblocker-liap/version/v1.10.0+1.20-beta

**Comment by Prabh-Saini** [comment]
Thank you! I must have missed that.
