### ISSUE TITLE
Crash in Rift

### ISSUE THREAD

**Issue by Fluboxer** [SkyblockerMod/Skyblocker#215]
So I got recent beta from Actions tab and it seems to crash me in Rift when I fight vampire slayer?
(java.lang.IllegalArgumentException: Illegal base64 character is spammed in logs - may be one of "hypixel multiversion moment" things)

```java
java.lang.IllegalArgumentException: Illegal base64 character 22
	at java.util.Base64$Decoder.decode0(Base64.java:847) ~[?:?]
	at java.util.Base64$Decoder.decode(Base64.java:566) ~[?:?]
	at java.util.Base64$Decoder.decode(Base64.java:589) ~[?:?]
	at com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo.validateProperty(YggdrasilServicesKeyInfo.java:141) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.lambda$getSecurePropertyValue$0(YggdrasilMinecraftSessionService.java:163) ~[authlib-4.0.43.jar:?]
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:706) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.noneMatch(ReferencePipeline.java:642) ~[?:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.getSecurePropertyValue(YggdrasilMinecraftSessionService.java:163) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.getTextures(YggdrasilMinecraftSessionService.java:116) ~[authlib-4.0.43.jar:?]
	at net.minecraft.class_1071.method_4653(class_1071.java:100) ~[client-intermediary.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[14:55:19] [Render thread/INFO]: [CHAT] ORB! Picked up +25 Motes, recovered +2? Rift Time!
[14:55:28] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "java.nio.ByteBuffer.rewind()" because "this.field_1555" is null
	at net.minecraft.class_287.method_1328(class_287.java:126) ~[client-intermediary.jar:?]
	at net.minecraft.class_276.method_1233(class_276.java:281) ~[client-intermediary.jar:?]
	at net.minecraft.class_276.method_22594(class_276.java:242) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_3254(class_761.java:614) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:884) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) ~[NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) ~[NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186) ~[NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) ~[NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) ~[NewLaunch.jar:?]

``` 

mods:
![изображение](https://github.com/SkyblockerMod/Skyblocker/assets/36457056/aa308068-3241-409a-93b8-740e56bf000e)
only mods I recently updated are CList, ChatUtils, FabricAPI and Skyblocker 

Thing: [crash-2023-07-28_14.55.29-client.txt](https://github.com/SkyblockerMod/Skyblocker/files/12194268/crash-2023-07-28_14.55.29-client.txt)

**Comment by Julienraptor01** [comment]
It's because hypixel send wrong base64 for skins

**Comment by Fluboxer** [comment]
Yes, however, my problem is not spam in console and/or lack of skin on few things. I included it just in case as it happened right before "[Render thread/ERROR]: Unreported exception thrown!"

My problem is that it crashed when you fight vampire slayer. I did few attempts and can't see any correlation as it crashes at different phases

**Comment by Julienraptor01** [comment]
> Yes, however, my problem is not spam in console and/or lack of skin on few things. I included it just in case as it happened right before "[Render thread/ERROR]: Unreported exception thrown!"
> 
> My problem is that it crashed when you fight vampire slayer. I did few attempts and can't see any correlation as it crashes at different phases

Make sure you are running on the latest build and try to disable features like the thing to remove stuff in log and vampire features until it doesn't crash anymore

**Comment by AzureAaron** [comment]
Does this happen only when you're using skyblocker?
I'd also like to ask if this happens with just skyblocker installed as the stack trace makes no mention of anything related to the mod

**Comment by Fluboxer** [comment]
Tested it without skyblocker - it works 

Tested it with only popular FPS mods - it works
Tested it with full kit - also works

then I noticed that I had VPN on. Turned it off and it happened again? ...
don't we all love bugs like this? :)

and no, it was functioning properly before. I will do few more tests and proceed to update this issue

**Comment by Fluboxer** [comment]
Update: after "well it seems to do something with connection" answer was quite obvious: it is krypton 
I probably accidentally enabled it first time and "testing with full kit" involved enabling it too

this is quite dumb - both me and situation as a whole. I will make few more tests just in case before closing it

**Comment by Fluboxer** [comment]
There is more to this clownfiesta 

Krypton's removal haven't solved the issue, however, looking at recently changed mods I noticed something
Reason why I went here to post issue is because it happened when I updated skyblocker. But with skyblocker I also updated Fabric API as it demanded newer version

Combo of "skyblocker-1.10.0-beta-97b049f+1.20.jar" (random few weeks old skyblocker from actions tab) and FabricAPI 0.85.0 was able to persist for whole session. For context - while I were checking mods and changing conditions in attempt to catch whatever the hell is that, it were crashing me instantly/in first minutes of existing at vampire slayer château 

Just like with krypton case, it may be pure luck so I will make more tests before heading to FabricAPI's github

**Comment by Fluboxer** [comment]
Another update on this stupid issue in case someone will ever get it too 

No, fabric API also weren't the cause - and at this point I decided to just brute-force mods until I either end up crashing in vanilla or find that sneaky mod that were breaking all that stuff

And after removal of ImmediatelyFast I was able to grind some vamps without crashes. In fact, I managed to grind whole timecharm without crashes on profile where I took down this mod

Maybe it was some weird interaction. Maybe IF wasn't guilty for this and I just got very very lucky - who knows, but if something that crashes 70% of the time in first second suddenly can persist for like 4-5 sessions - I would consider it working properly

**Comment by AzureAaron** [comment]
I can confirm this is indeed an issue with IF, their optimized buffer logic can cause the `BufferBuilder`'s internal buffer to be null sometimes which is impossible in vanilla.

I would recommend avoiding the use of IF with Skyblocker, since it could trigger random crashing like you experienced here.

**Comment by Julienraptor01** [comment]
i don't think the issue was cause by IF as i just can't reproduce, but talking with IF's dev, he told me that the culprit was probably dashloader
