### ISSUE TITLE
Breaks when used with Optifine and Optifabric

### ISSUE THREAD

**Issue by pikachub2005** [SkyblockerMod/Skyblocker#247]
Does anyone know what causes this, or a way to fix it? I'd prefer not to lose Optifine since I'm using it for the Fresh Animations resource pack.
![image](https://github.com/SkyblockerMod/Skyblocker/assets/74213212/7550dc1a-628e-4b08-9fc2-365b07fae12c)
It also crashes when I try to join hypixel
```
---- Minecraft Crash Report ----

Time: 2023-08-17 01:39:06
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5944.setSampler(int, Object)" because "shaderinstance" is null
	at net.minecraft.class_761.method_3251(class_761.java:2365)
	at net.minecraft.class_761.method_22710(class_761.java:1716)
	at net.minecraft.class_757.method_3188(class_757.java:1651)
	at net.minecraft.class_757.method_3192(class_757.java:1279)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_761.method_3251(class_761.java:2365)
	at net.minecraft.class_761.method_22710(class_761.java:1716)
	at net.minecraft.class_757.method_3188(class_757.java:1651)

-- Affected level --
Details:
	All players: 7 total; [class_746['Bentl2'/3049671, l='ClientLevel', x=-3.69, y=70.00, z=0.80], class_745['90khr4r16j'/89, l='ClientLevel', x=9.50, y=67.00, z=-4.50], class_745['83yl6sln1o'/38, l='ClientLevel', x=24.50, y=68.00, z=-1.50], class_745['49772r2973'/39, l='ClientLevel', x=26.50, y=68.00, z=-5.50], class_745['d0v6x753bw'/40, l='ClientLevel', x=24.50, y=68.00, z=2.50], class_745['7h096495xa'/41, l='ClientLevel', x=26.50, y=68.00, z=6.50], class_745['7yl19ia781'/90, l='ClientLevel', x=33.50, y=67.00, z=14.50]]
	Chunk stats: 5041, 169
	Level dimension: minecraft:overworld
	Level spawn location: World: (-4,70,0), Section: (at 12,6,0 in -1,4,0; chunk contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 87006238 game time, 1342 day time
	Server brand: Hypixel BungeeCord (1.3.22) <- vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:590)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: vanilla, fabric
	Recovery: Yes
	Recovery reason: java.util.concurrent.CompletionException: java.lang.AbstractMethodError: Receiver class net.minecraft.class_1088$class_7778 does not define or inherit an implementation of the resolved method 'abstract java.util.function.Function getModelTextureGetter()' of interface net.minecraftforge.client.extensions.IForgeModelBaker.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.AbstractMethodError: Receiver class net.minecraft.class_1088$class_7778 does not define or inherit an implementation of the resolved method 'abstract java.util.function.Function getModelTextureGetter()' of interface net.minecraftforge.client.extensions.IForgeModelBaker.
	at net.minecraft.class_806.<init>(class_806.java:49)
	at net.minecraft.class_793.method_3440(class_793.java:143)
	at net.minecraft.class_793.method_3446(class_793.java:213)
	at net.minecraft.class_1088$class_7778.redirect$zep000$fabric-model-loading-api-v1$invokeModifyAfterBake(class_1088.java:565)
	at net.minecraft.class_1088$class_7778.method_45873(class_1088.java:423)
	at net.minecraft.class_1088.method_45877(class_1088.java:211)
	at java.base/java.util.HashMap$KeySet.forEach(HashMap.java:1008)
	at net.minecraft.class_1088.method_45876(class_1088.java:206)
	at net.minecraft.class_1092.method_45883(class_1092.java:145)
	at net.minecraft.class_1092.method_45885(class_1092.java:92)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 6 more


-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 935495376 bytes (892 MiB) / 2181038080 bytes (2080 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i7-1355U
	Identifier: Intel64 Family 6 Model 186 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2.61
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0xa7a1
	Graphics card #0 versionInfo: DriverVersion=31.0.101.4032
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 6.40
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 6.40
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 26378.63
	Virtual memory used (MB): 23577.86
	Swap memory total (MB): 10270.76
	Swap memory used (MB): 785.99
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		fabric-api: Fabric API 0.87.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.2+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.2+6bdb2ed077
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.2+6bdb2ed077
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabricloader: Fabric Loader 0.14.22
		java: Java HotSpot(TM) 64-Bit Server VM 17
		minecraft: Minecraft 1.20.1
		optifabric: OptiFabric 1.13.25
			mm: Manningham Mills 2.3
		skyblocker: Skyblocker 1.12.0+1.20.1
			cloth-config: Cloth Config v11 11.1.106
				cloth-basic-math: cloth-basic-math 0.6.1
			com_github_cbyrneee_betterinject: BetterInject 0.1.3
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.9
			com_logisticscraft_occlusionculling: occlusionculling 0.0.7-SNAPSHOT
			meteordevelopment_discord-ipc: discord-ipc 1.1
			org_eclipse_jgit_org_eclipse_jgit: org.eclipse.jgit 6.4.0.202211300538-r
			renderer: Renderer 1.0
				satin: Satin 1.13.0
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Intel(R) Iris(R) Xe Graphics GL version 3.2.0 - Build 31.0.101.4032, Intel
	Window size: 1920x1111
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'optifine'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: en_us
	CPU: 12x 13th Gen Intel(R) Core(TM) i7-1355U
	OptiFine Version: OptiFine_1.20.1_HD_U_I5
	OptiFine Build: 20230707-211226
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 - Build 31.0.101.4032
	OpenGlRenderer: Intel(R) Iris(R) Xe Graphics
	OpenGlVendor: Intel
	CpuCount: 12

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.20.1
	OptiFine jar version: OptiFine_1.20.1_HD_U_I5
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/bbent/AppData/Roaming/PrismLauncher/instances/Hypixel/.minecraft/.optifine/OptiFine_1.20.1_HD_U_I5/Optifine-mapped.jar
	OptiFabric error: <None>
```

**Comment by pikachub2005** [comment]
Hold on, looks like I didn't look around enough. This is just an optifabric problem, and I just noticed it because I had to update the fabric api. My bad

**Comment by Julienraptor01** [comment]
There are alternative to optifine on fabric that works as well and will cause way less issues
You can by example take a look at [Fabulously Optimized](https://modrinth.com/modpack/fabulously-optimized) which - contains all of the OptiFine parity mods on fabric
Thanks to ETF and EMF mods, Fresh Animations should be entirely compatible
