### ISSUE TITLE
Quick Navigation icons show up with black background

### ISSUE THREAD

**Issue by amyavi** [SkyblockerMod/Skyblocker#329]
### What happened?

Quick Navigation icons show up with black background instead of the usual creative tab icon background.

Steps to reproduce:
- Join skyblock
- Open inventory with quick navigation enabled

### Screenshots

![image](https://github.com/SkyblockerMod/Skyblocker/assets/144570677/72646607-8f8a-4916-8a4f-853244e32d82)

### Log output

[latest.log](https://github.com/SkyblockerMod/Skyblocker/files/12709562/latest.log)

### Minecraft Version

Minecraft 1.20.2

### Skyblocker Version

1.14.0+1.20.2

### Additional context

The relevant exception is the following:
```
[16:49:42] [Render thread/WARN]: Failed to load texture: minecraft:textures/gui/container/creative_inventory/tabs.png
java.io.FileNotFoundException: minecraft:textures/gui/container/creative_inventory/tabs.png
	at net.minecraft.class_5912.method_43043(class_5912.java:21) ~[client-intermediary.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_5912.getResourceOrThrow(class_5912.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049$class_4006.method_18156(class_1049.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_18153(class_1049.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_1049.method_4625(class_1049.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_24303(class_1060.java:96) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4616(class_1060.java:68) ~[client-intermediary.jar:?]
	at net.minecraft.class_1060.method_4619(class_1060.java:118) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem._setShaderTexture(RenderSystem.java:1232) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.setShaderTexture(RenderSystem.java:1225) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_25295(class_332.java:442) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_25297(class_332.java:433) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_25291(class_332.java:405) ~[client-intermediary.jar:?]
	at net.minecraft.class_332.method_25302(class_332.java:394) ~[client-intermediary.jar:?]
	at me.xmrvizzy.skyblocker.skyblock.quicknav.QuickNavButton.method_48579(QuickNavButton.java:74) ~[skyblocker-1.14.0+1.20.2.jar:?]
	at net.minecraft.class_339.method_25394(class_339.java:73) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25394(class_437.java:121) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_25394(class_465.java:100) ~[client-intermediary.jar:?]
	at net.minecraft.class_485.method_25394(class_485.java:30) ~[client-intermediary.jar:?]
	at net.minecraft.class_490.method_25394(class_490.java:83) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:946) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1275) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[minecraft-1.20.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
```
It happens because in 1.20.2 the creative tab icons were moved to `minecraft:textures/gui/container/creative_inventory/tab_<bottom|top>_<unselected|selected>_<1-7>.png`.

**Comment by Julienraptor01** [comment]
yeah latest stable skyblocker isn't compatible with mc 1.20.2, stay on 1.20.1 at the moment
you can use #324 if you want 1.20.2 support tho
build artifacts : https://github.com/SkyblockerMod/Skyblocker/suites/16468817340/artifacts/941205969
