### ISSUE TITLE
Dungeon Secret Waypoints let my game crash

### ISSUE THREAD

**Issue by ItzGreenCat** [SkyblockerMod/Skyblocker#372]
### Minecraft Version

1.20.1

### Skyblocker Version

  skyblocker-1.14.0+1.20.1.jar

### Reproduction Steps

1.Enable the Dungeon Secret Waypoint
2.Enter dungeon and play a while
3.game crashed

### Crash Report file and latest.log

```shell
java.lang.NullPointerException: Cannot invoke "java.nio.ByteBuffer.rewind()" because "this.field_1555" is null
	at net.minecraft.class_287.method_1328(class_287.java:126)
	at net.minecraft.class_276.method_1233(class_276.java:281)
	at net.minecraft.class_276.method_22594(class_276.java:242)
	at net.minecraft.class_761.method_3254(class_761.java:614)
	at net.minecraft.class_757.method_3192(class_757.java:884)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
-------------------------------------------------------------------------------------------
Mixins in Stacktrace:
	net.minecraft.class_287:
		net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo (mixins.iris.vertexformat.json)
		net.coderbot.batchedentityrendering.mixin.MixinBufferBuilder (iris-batched-entity-rendering.mixins.json)
		me.jellysquid.mods.sodium.mixin.core.render.immediate.consumer.BufferBuilderMixin (sodium.mixins.json)
		me.jellysquid.mods.sodium.mixin.features.render.immediate.buffer_builder.BufferBuilderMixin (sodium.mixins.json)
		me.jellysquid.mods.sodium.mixin.features.render.immediate.buffer_builder.intrinsics.BufferBuilderMixin (sodium.mixins.json)
		net.raphimc.immediatelyfast.injection.mixins.core.MixinBufferBuilder (immediatelyfast.mixins.json)
		team.creative.creativecore.mixin.BufferBuilderAccessor (creativecore.mixins.json)
		net.coderbot.batchedentityrendering.mixin.MixinBufferBuilder_SegmentRendering (iris-batched-entity-rendering.mixins.json)
		me.jellysquid.mods.sodium.mixin.features.render.immediate.buffer_builder.sorting.BufferBuilderMixin (sodium.mixins.json)
		net.coderbot.iris.mixin.vertices.MixinBufferBuilder (mixins.iris.vertexformat.json)
	net.minecraft.class_276:
		ladysnake.satin.mixin.client.gl.DepthGlFramebufferMixin (mixins.satin.client.json)
		net.coderbot.iris.mixin.MixinRenderTarget (mixins.iris.json)
		net.coderbot.iris.mixin.state_tracking.MixinRenderTarget (mixins.iris.json)
		ladysnake.satin.mixin.client.gl.CustomFormatFramebufferMixin (mixins.satin.client.json)
	net.minecraft.class_761:
		dev.tr7zw.entityculling.mixin.WorldRendererMixin (entityculling.mixins.json)
		net.coderbot.iris.mixin.LevelRendererAccessor (mixins.iris.json)
		me.flashyreese.mods.sodiumextra.mixin.sky.MixinWorldRenderer (sodium-extra.mixins.json)
		me.flashyreese.mods.sodiumextra.mixin.particle.MixinWorldRenderer (sodium-extra.mixins.json)
		net.blay09.mods.balm.mixin.LevelRendererMixin (balm.mixins.json)
		me.jellysquid.mods.sodium.mixin.features.options.weather.WorldRendererMixin (sodium.mixins.json)
		com.noxcrew.noxesium.mixin.entity.LevelRendererMixin (noxesium.mixins.json)
		com.teamderpy.shouldersurfing.mixins.MixinLevelRenderer (shouldersurfing.mixins.json)
		net.coderbot.iris.mixin.vertices.immediate.MixinLevelRenderer (mixins.iris.vertexformat.json)
		me.xmrvizzy.skyblocker.mixin.accessor.WorldRendererAccessor (skyblocker.mixins.json)
		me.flashyreese.mods.sodiumextra.mixin.stars.MixinWorldRenderer (sodium-extra.mixins.json)
		com.noxcrew.noxesium.mixin.beacon.BeaconRenderingMixin (noxesium.mixins.json)
		me.juancarloscp52.bedrockify.mixin.client.features.bedrockShading.sunGlare.WorldRendererMixin (bedrockify.mixins.json)
		foundationgames.enhancedblockentities.mixin.WorldRendererMixin (enhancedblockentities.mixins.json)
		net.coderbot.iris.mixin.fabulous.MixinDisableFabulousGraphics (mixins.iris.json)
		net.coderbot.iris.mixin.shadows.MixinLevelRenderer (mixins.iris.json)
		net.coderbot.batchedentityrendering.mixin.MixinLevelRenderer_EntityListSorting (iris-batched-entity-rendering.mixins.json)
		me.jellysquid.mods.sodium.mixin.features.render.world.clouds.WorldRendererMixin (sodium.mixins.json)
		net.fabricmc.fabric.mixin.resource.loader.client.KeyedResourceReloadListenerClientMixin (fabric-resource-loader-v0.client.mixins.json)
		net.fabricmc.fabric.mixin.client.rendering.WorldRendererMixin (fabric-rendering-v1.mixins.json)
		net.coderbot.iris.mixin.shadows.MixinPreventRebuildNearInShadowPass (mixins.iris.json)
		net.coderbot.iris.mixin.MixinLevelRenderer (mixins.iris.json)
		net.coderbot.iris.compat.sodium.mixin.sky.MixinLevelRenderer (mixins.iris.compat.sodium.json)
		ladysnake.satin.mixin.client.event.WorldRendererMixin (mixins.satin.client.json)
		me.flashyreese.mods.sodiumextra.mixin.sun_moon.MixinWorldRenderer (sodium-extra.mixins.json)
		me.jellysquid.mods.sodium.mixin.core.render.world.WorldRendererMixin (sodium.mixins.json)
		net.coderbot.batchedentityrendering.mixin.MixinLevelRenderer (iris-batched-entity-rendering.mixins.json)
		me.xmrvizzy.skyblocker.mixin.WorldRendererMixin (skyblocker.mixins.json)
		me.jellysquid.mods.sodium.mixin.features.render.gui.outlines.WorldRendererMixin (sodium.mixins.json)
		net.coderbot.iris.mixin.sky.MixinLevelRenderer_SunMoonToggle (mixins.iris.json)
		net.coderbot.iris.mixin.fantastic.MixinLevelRenderer (mixins.iris.fantastic.json)
------------------------------------------------------------------------------------------------
-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 5.15.0-56-generic
	Java Version: 17.0.7, Flathub
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Flathub
	Memory: 2470810136 bytes (2356 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: GP107 [GeForce GTX 1050 Ti]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x1c82
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 10028.98
	Virtual memory used (MB): 8630.71
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms512m -Xmx4096m
----------------------------------------------------------------------------
Fabric Mods: 
		ambientsounds: AmbientSounds 5.2.20
		architectury: Architectury 9.0.8
		bactromod: BactroMod 1.7
		balm-fabric: Balm 7.0.4
		bedrockify: BedrockIfy 1.9+mc1.20
		better_end_sky: Better End Sky 0.2.1+1.20
		betterbeds: Better Beds 1.3.0
		betterf3: BetterF3 7.0.0
		bettermounthud: Better Mount HUD 1.2.2
		betterstats: Better Statistics Screen 2.10.3+1.20.1
			tcdcommons: TCD Commons API 2.10.2+1.20.1
		blur: Blur (Fabric) 3.1.0
		borderlessmining: Borderless Mining 1.1.8+1.20.1
		bsvsb: Better Sodium Video Settings Button 3.0.3
		butter: butter 1.1.1+1.20.1
		cameraoverhaul: Camera Overhaul 1.4.0-fabric-universal
		capes: Capes 1.5.2+1.20
		chat_heads: Chat Heads 0.10.16
		chunksfadein: Chunks Fade In 1.0.4-1.20.1
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		chunky: Chunky 1.3.92
		citresewn: CIT Resewn 1.1.3+1.20
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.20
		clearvoid: Clear Void 1.3.0
		clienttweaks: Client Tweaks 11.0.0
		cloth-config: Cloth Config v11 11.0.99
			cloth-basic-math: cloth-basic-math 0.6.1
		completeconfig: CompleteConfig 2.4.0
			completeconfig-base: completeconfig-base 2.4.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.4.0
			completeconfig-gui-yacl: completeconfig-gui-yacl 2.4.0
		continuity: Continuity 3.0.0-beta.3+1.20.1
		creativecore: CreativeCore 2.10.24
			net_minecraftforge_eventbus: eventbus 6.0.3
		crso4: Chromium-II-Sulfate 1.0-SNAPSHOT
		cull-less-leaves: Cull Less Leaves 1.2.0
		dcch: DCCH 2.0+1.17
		dynamicfps: Dynamic FPS 2.4.0
		eatinganimationid: Eating Animation 1.9.4+1.20
		emi: EMI 1.0.22+1.20.1+fabric
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
		entity-view-distance: Entity View Distance 1.1.2+1.20
			spruceui: SpruceUI 5.0.0+1.20
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20
		explosiveenhancement: Explosive Enhancement 1.2.1-1.20.x
		fabric-api: Fabric API 0.89.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.0+0883a8d477
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.1+195226a777
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.9.6+kotlin.1.8.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.22
		fallingleaves: Falling Leaves 1.15.1+1.20.1
		faster_entity_animations: FastAnim 1.6
		ferritecore: FerriteCore 6.0.0
		forcegl20: ForceGL20 1.1.0
		forgeconfigapiport: Forge Config API Port 8.0.0
		guild_bot: GuildBot 1.0-SNAPSHOT
		highlighter: Highlighter 1.1.6
		iceberg: Iceberg 1.1.14
		immediatelyfast: ImmediatelyFast 1.1.15+1.20.1
			net_lenni0451_reflect: Reflect 1.1.0
		indium: Indium 1.0.27+mc1.20.1
		inventory_control_tweaks: Inventory Control Tweaks 1.3.25
		iris: Iris 1.6.9
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemborders: Item Borders 1.2.0
		itemphysic: ItemPhysic 1.6.10
		jade: Jade 11.1.4
		java: OpenJDK 64-Bit Server VM 17
		konkrete: Konkrete 1.6.1
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		ksyxis: Ksyxis 1.1
		lithium: Lithium 0.11.2
		logcleaner: Log Cleaner 1.0.0
		make_bubbles_pop: Make Bubbles Pop Mod 0.1.1-fabric
		minecraft: Minecraft 1.20.1
		mixintrace: MixinTrace 1.1.1+1.17
		modelfix: Model Gap Fix 1.14
		modmenu: Mod Menu 7.1.0
		no_more_purple: No More Purple 1.2.1
		nochatreports: No Chat Reports 1.20.1-v2.2.2
		noxesium: Noxesium 1.0.3+9b339b0
			com_noxcrew_noxesium_api_: api 1.0.3+9b339b0
		prism: Prism 1.0.5
		proxyserver: Proxy Server 1.0-SNAPSHOT
			io_netty_netty-codec-socks: netty-codec-socks 4.1.82.Final
			io_netty_netty-handler-proxy: netty-handler-proxy 4.1.82.Final
		puzzleslib: Puzzles Lib 8.0.7
		pvplegacyutils: PvP Legacy Utils 1.1.0
			pvplegacyutils-1-19-3: PvP Legacy Utils for 1.19.3+ 1.1.0
			pvplegacyutils-1-19-4: PvP Legacy Utils for 1.19.4+ 1.1.0
		rrls: Remove Reloading Screen 1.20.1-3.1.0-fabric
		servercore: ServerCore 1.3.7+1.20.1
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		shouldersurfing: Shoulder Surfing Reloaded 2.4
		skyblocker: Skyblocker 1.14.0+1.20.1
			com_github_cbyrneee_betterinject: BetterInject 0.1.3
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.9
			com_logisticscraft_occlusionculling: occlusionculling 0.0.7-SNAPSHOT
			meteordevelopment_discord-ipc: discord-ipc 1.1
			org_eclipse_jgit_org_eclipse_jgit: org.eclipse.jgit 6.4.0.202211300538-r
			renderer: Renderer 1.0
				satin: Satin 1.14.0
		smoothparticles: Smooth Particles 1.1.1-1.20.1
		sodium: Sodium 0.5.3
		sodium-extra: Sodium Extra 0.5.1+mc1.20.1-build.112
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		styledchat: Styled Chat 2.2.0+1.20
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			placeholder-api: Placeholder API 2.1.1+1.20
			player-data-api: Player Data API 0.2.2+1.19.3
			predicate-api: Predicate API 0.1.2+1.20
		swordblocking: Sword Blocking 1.3.1
			midnightlib: MidnightLib 1.4.1
		tia: Tiny Item Animations 1.20-1.1
		timestamp_chat: Timestamp Chat 2.3.0+1.19.3
		tipthescales: Tip The Scales 9.0.0.1
		tooltipfix: ToolTip Fix 1.1.1-1.20
		tooltipscroll: Tooltip Scroll v1.2.5-1.20
		uglyscoreboardfix: Ugly Scoreboard Fix 2.10.0
		vectorientation: Vectorientation 1.0.1a
		visuality: Visuality 0.7.0+1.20
		visualoverhaul: VisualOverhaul 5.0.1
		whats_that_slot: What's That Slot? 1.3.4+1.20.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
----------------------------------------------------------------------------------------
Loaded Shaderpack: Sildurs Vibrant Shaders v1.29 Extreme.zip
---------------------------------------------------------------------------------
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. <texture> is not a valid texture name.' x 26
	Using VBOs: Yes
```

### Additional context

If i disable the dungeon waypoints the game wont crash
According to Stacktrace , it seems that WorldRenderer cause the crash
I provided the GL Debug Messages and the Mod List
Please fix this crash problem

**Comment by AzureAaron** [comment]
This is caused by using an incompatible version of immediately fast, updating to the latest version of it will fix your issue.

**Comment by ItzGreenCat** [comment]
> This is caused by using an incompatible version of immediately fast, updating to the latest version of it will fix your issue.

Which version should i use?
The latest version?

**Comment by AzureAaron** [comment]
> > This is caused by using an incompatible version of immediately fast, updating to the latest version of it will fix your issue.
> 
> Which version should i use? The latest version?

I would recommend using the latest version, although IF 1.1.27+ has the fix for the crash

**Comment by ItzGreenCat** [comment]
ok tysm
