### ISSUE TITLE
Higher or Lower Slover doesn't work

### ISSUE THREAD

**Issue by ItzGreenCat** [SkyblockerMod/Skyblocker#376]
### What happened?

just like title,it cannot work

### Log output

java.lang.NumberFormatException: For input string: "1,334"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:786) ~[?:?]
	at me.xmrvizzy.skyblocker.skyblock.dungeon.DungeonBlaze.getBlazesInWorld(DungeonBlaze.java:66) ~[skyblocker-1.14.0+1.20.1.jar:?]
	at me.xmrvizzy.skyblocker.skyblock.dungeon.DungeonBlaze.update(DungeonBlaze.java:49) ~[skyblocker-1.14.0+1.20.1.jar:?]
	at me.xmrvizzy.skyblocker.utils.scheduler.Scheduler$ScheduledTask.run(Scheduler.java:137) ~[skyblocker-1.14.0+1.20.1.jar:?]
	at me.xmrvizzy.skyblocker.utils.scheduler.Scheduler$CyclicTask.run(Scheduler.java:120) ~[skyblocker-1.14.0+1.20.1.jar:?]
	at me.xmrvizzy.skyblocker.utils.scheduler.Scheduler.runTask(Scheduler.java:93) ~[skyblocker-1.14.0+1.20.1.jar:?]
	at me.xmrvizzy.skyblocker.utils.scheduler.Scheduler.tick(Scheduler.java:77) ~[skyblocker-1.14.0+1.20.1.jar:?]
	at me.xmrvizzy.skyblocker.SkyblockerMod.tick(SkyblockerMod.java:121) ~[skyblocker-1.14.0+1.20.1.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43) ~[fabric-lifecycle-events-v1-2.2.2+b3afc78b77-2797ff451c2ba64e.jar:?]
	at net.minecraft.class_310.handler$bfi000$fabric-lifecycle-events-v1$onEndTick(class_310.java:8522) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1957) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]

### Minecraft Version

1.20.1

### Skyblocker Version

skyblocker-1.14.0+1.20.1.jar

### Additional context

just like log,its just a simple Number Formatting Exception,please fix this problem

**Comment by Julienraptor01** [comment]
You need to update the mod, this has been fixed

**Comment by ItzGreenCat** [comment]
> You need to update the mod, this has been fixed

But i already using the latest version:mod version 1.14.0

**Comment by kevinthegreat1** [comment]
The latest version for 1.20.1 is 1.14.1. An update for 1.20.2 will be coming very soon.
