### ISSUE TITLE
Deviation from vanilla behaviour for parsing leather armor colour causing a crash for some NBTs

### ISSUE THREAD

**Issue by nea89o** [SkyblockerMod/Skyblocker#462]
### What happened?

When parsing armor colour for exotic checking, the color number is first converted to a string, and then converted to an int. This can cause exceptions with double tags, which get parsed by the vanilla DyeableItem just fine.

https://github.com/SkyblockerMod/Skyblocker/blob/cf1954c11258894b2e825f776d57ad12648f0f42/src/main/java/de/hysky/skyblocker/skyblock/item/tooltip/ItemTooltip.java#L186-L190

### Log output

```
[19:03:35] [Render thread/INFO]: [STDERR]: java.lang.NumberFormatException: For input string: "315347.0d"
[19:03:35] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.Integer.parseInt(Integer.java:668)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at java.base/java.lang.Integer.parseInt(Integer.java:786)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at de.hysky.skyblocker.skyblock.item.tooltip.ItemTooltip.getTooltip(ItemTooltip.java:189)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback.lambda$static$0(ItemTooltipCallback.java:34)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1799.handler$bid000$fabric-item-api-v1$getTooltip(class_1799.java:4120)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1799.method_7950(class_1799.java:796)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition.tryGetItemStackToolTip(ItemEntryDefinition.java:231)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.getTooltip(ItemEntryDefinition.java:369)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:195)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at moe.nea.firmament.rei.NEUItemEntryRenderer.getTooltip(NEUItemEntryRenderer.kt:46)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:195)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.api.common.entry.EntryStack.getTooltip(EntryStack.java:225)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.getCurrentTooltip(EntryWidget.java:444)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListStackEntry.getCurrentTooltip(EntryListStackEntry.java:204)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.queueTooltip(EntryWidget.java:432)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.gui.widget.DisplayedEntryWidget.queueTooltip(DisplayedEntryWidget.java:60)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderBatched(BatchedEntryRendererManager.java:228)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:128)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.gui.widget.entrylist.PaginatedEntryListWidget.renderEntries(PaginatedEntryListWidget.java:109)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.gui.widget.entrylist.EntryListWidget.method_25394(EntryListWidget.java:196)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:348)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:244)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.registry.screen.ScreenRegistryImpl$5.render(ScreenRegistryImpl.java:375)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$onApplied$5(DefaultScreenOverlayRenderer.java:91)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at me.shedaniel.rei.impl.client.registry.screen.DefaultScreenOverlayRenderer.lambda$new$1(DefaultScreenOverlayRenderer.java:61)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_465.handler$zco000$architectury$renderBackground(class_465.java:723)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_465.method_25420(class_465.java:172)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_25394(class_437.java:119)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_465.method_25394(class_465.java:100)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_485.method_25394(class_485.java:30)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_490.method_25394(class_490.java:83)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_437.method_47413(class_437.java:110)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_757.method_3192(class_757.java:946)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1275)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:856)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:253)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:125)
[19:03:35] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

### Minecraft Version

1.20.2

### Skyblocker Version

1.16.0+1.20.2

**Comment by AzureAaron** [comment]
Thanks for the code analysis!
