### ISSUE TITLE
Garden Visitor Helper not work and game crashed.

### ISSUE THREAD

**Issue by AC19970** [SkyblockerMod/Skyblocker#577]
### Minecraft Version

1.20.4

### Skyblocker Version

skyblocker-1.18.1+1.20.4.jar

### Reproduction Steps

When I enter the garden and open the visitor's menu, the game crashes with the error documented in the log.

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-02-27 10:50:06
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "java.util.Map.values()" because the return value of "io.github.moulberry.repo.NEUItems.getItems()" is null
	at de.hysky.skyblocker.skyblock.garden.VisitorHelper.getCachedItem(VisitorHelper.java:152)
	at de.hysky.skyblocker.skyblock.garden.VisitorHelper.drawItemEntryWithHover(VisitorHelper.java:141)
	at de.hysky.skyblocker.skyblock.garden.VisitorHelper.drawScreenItems(VisitorHelper.java:132)
	at de.hysky.skyblocker.skyblock.garden.VisitorHelper.renderScreen(VisitorHelper.java:53)
	at de.hysky.skyblocker.skyblock.garden.VisitorHelper.lambda$init$0(VisitorHelper.java:46)
	at net.fabricmc.fabric.impl.client.screen.ScreenEventFactory.lambda$createAfterRenderEvent$4(ScreenEventFactory.java:48)
	at net.minecraft.class_757.wrapOperation$zlg000$fabric-screen-api-v1$onRenderScreen(class_757.java:2112)
	at net.minecraft.class_757.method_3192(class_757.java:931)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by AzureAaron** [comment]
Do you have the full log file?

**Comment by kevinthegreat1** [comment]
We need the full `latest.log`. You can upload it to mclo.gs which automatically strips username.

**Comment by kevinthegreat1** [comment]
Also, you can try if #579 fixes your issue.
