### ISSUE TITLE
crash after launching 

### ISSUE THREAD

**Issue by virus00020** [SkyblockerMod/Skyblocker#588]
### Minecraft Version

1.20.4

### Skyblocker Version

skyblocker-1.18.1

### Reproduction Steps

1. launch 
2. it will crash
3. 

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-03-08 10:14:40
Description: Initializing game

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_4599 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.minecraft.class_310.<init>(class_310.java:601)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 9 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [citresewn-defaults.mixins.json:types.enchantment.BufferBuilderStorageAccessor from mod citresewn-defaults] from phase [DEFAULT] in config [citresewn-defaults.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 12 more
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching field_20957:Ljava/util/SortedMap; in net/minecraft/class_4599 for citresewn-defaults.mixins.json:types.enchantment.BufferBuilderStorageAccessor from mod citresewn-defaults->@Accessor[FIELD_GETTER]::getEntityBuilders()Ljava/util/SortedMap; [INJECT Applicator Phase -> citresewn-defaults.mixins.json:types.enchantment.BufferBuilderStorageAccessor from mod citresewn-defaults -> Apply Accessors ->  -> Locate -> citresewn-defaults.mixins.json:types.enchantment.BufferBuilderStorageAccessor from mod citresewn-defaults->@Accessor[FIELD_GETTER]::getEntityBuilders()Ljava/util/SortedMap;]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:519)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:502)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:476)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1411)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1071)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 12 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.minecraft.class_310.<init>(class_310.java:601)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:6.1.7601.26022 (win7sp1_ldr_escrow.220707-1853):Microsoft Corporation
		CFGMGR32.dll:Configuration Manager DLL:6.1.7601.23403 (win7sp1_ldr.160325-0600):Microsoft Corporation
		CLBCatQ.DLL:COM+ Configuration Catalog:2001.12.8531.23403 (win7sp1_ldr.160325-0600):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (win7_rtm.090713-1255):Microsoft Corporation
		CRYPT32.dll:Crypto API32:6.1.7601.25976 (win7sp1_ldr_escrow.220511-1608):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:6.1.7601.26022 (win7sp1_ldr_escrow.220707-1853):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:6.1.7601.24499 (win7sp1_ldr.190612-0600):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:6.1.7601.25976 (win7sp1_ldr_escrow.220511-1608):Microsoft Corporation
		DCIMAN32.dll:DCI Manager:6.1.7601.25682 (win7sp1_ldr_escrow.210712-1746):Microsoft Corporation
		DDRAW.dll:Microsoft DirectDraw:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		DEVOBJ.dll:Device Information Set DLL:6.1.7601.23403 (win7sp1_ldr.160325-0600):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		GDI32.dll:GDI Client DLL:6.1.7601.25948 (win7sp1_ldr_escrow.220411-1730):Microsoft Corporation
		GLU32.dll:OpenGL Utility Library DLL:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:6.1.7601.23403 (win7sp1_ldr.160325-0600):Microsoft Corporation
		Iphlpapi.DLL:IP Helper API:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:6.1.7601.25954 (win7sp1_ldr_escrow.220429-1730):Microsoft Corporation
		LPK.dll:Language Pack:6.1.7601.25682 (win7sp1_ldr_escrow.210712-1746):Microsoft Corporation
		MMDevApi.dll:MMDevice API:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		MSASN1.dll:ASN.1 Runtime APIs:6.1.7601.23403 (win7sp1_ldr.160325-0600):Microsoft Corporation
		MSCTF.dll:MSCTF Server DLL:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		NLAapi.dll:Network Location Awareness 2:6.1.7601.24557 (win7sp1_ldr_escrow.200610-1907):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:6.1.7601.23889 (win7sp1_ldr.170810-1615):Microsoft Corporation
		OLEAUT32.dll::6.1.7601.24596:Microsoft Corporation
		OpenAL.dll:Main implementation library:1.23.0:
		POWRPROF.dll:Power Profile Helper DLL:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		PROPSYS.dll:Microsoft Property System:7.00.7601.23403 (win7sp1_ldr.160325-0600):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		RpcRtRemote.dll:Remote RPC Extension:6.1.7601.17514 (win7sp1_rtm.101119-1850):Microsoft Corporation
		SETUPAPI.dll:Windows Setup API:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:6.1.7601.23403 (win7sp1_ldr.160325-0600):Microsoft Corporation
		SHLWAPI.dll:Shell Light-weight Utility Library:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:6.1.7601.23403 (win7sp1_ldr.160325-0600):Microsoft Corporation
		USERENV.dll:Userenv:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		USP10.dll:Uniscribe Unicode script processor:1.0626.7601.25734 (win7sp1_ldr_escrow.210913-1723):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:6.1.7601.23403 (win7sp1_ldr.160325-0600):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		WINMM.dll:MCI API DLL:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		WINNSI.DLL:Network Store Information RPC interface:6.1.7601.23889 (win7sp1_ldr.170810-1615):Microsoft Corporation
		WINTRUST.dll:Microsoft Trust Verification APIs:6.1.7601.25976 (win7sp1_ldr_escrow.220511-1608):Microsoft Corporation
		WLDAP32.dll:Win32 LDAP API DLL:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		WTSAPI32.dll:Windows Remote Desktop Session Host Server SDK APIs:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		api-ms-win-core-file-l1-2-0.dll:ApiSet Stub DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-core-file-l2-1-0.dll:ApiSet Stub DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-core-localization-l1-2-0.dll:ApiSet Stub DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-core-processthreads-l1-1-1.dll:ApiSet Stub DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-core-synch-l1-2-0.dll:ApiSet Stub DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-core-timezone-l1-1-0.dll:ApiSet Stub DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-crt-convert-l1-1-0.dll:ApiSet Stub DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-crt-environment-l1-1-0.dll:ApiSet Stub DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-crt-filesystem-l1-1-0.dll:ApiSet Stub DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-crt-heap-l1-1-0.dll:ApiSet Stub DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-crt-locale-l1-1-0.dll:ApiSet Stub DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-crt-math-l1-1-0.dll:ApiSet Stub DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-crt-runtime-l1-1-0.dll:ApiSet Stub DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-crt-stdio-l1-1-0.dll:ApiSet Stub DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-crt-string-l1-1-0.dll:ApiSet Stub DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-crt-time-l1-1-0.dll:ApiSet Stub DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		api-ms-win-crt-utility-l1-1-0.dll:ApiSet Stub DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		awt.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		bcrypt.dll:Windows Cryptographic Primitives Library:6.1.7601.26022 (win7sp1_ldr_escrow.220707-1853):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client Service:6.1.7601.24560 (win7sp1_ldr_escrow.200814-1857):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 Client:6.1.7601.24560 (win7sp1_ldr_escrow.200814-1857):Microsoft Corporation
		dinput8.dll:Microsoft DirectInput:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		dwmapi.dll:Microsoft Desktop Window Manager API:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec User-Mode API:6.1.7601.23403 (win7sp1_ldr.160325-0600):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		icm32.dll:Microsoft Color Management Module (CMM):6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		ig7icd64.dll:OpenGL(R) Driver for Intel(R) Graphics Accelerator:10.18.10.5161:Intel Corporation
		igdusc64.dll:Unified Shader Compiler for Intel(R) Graphics Accelerator:10.18.10.5161:Intel Corporation
		java.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		javaw.exe:OpenJDK Platform binary:17.0.8.0:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jli.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jna3157132445372802000.dll:JNA native library:6.1.6:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jvm.dll:OpenJDK 64-Bit server VM:17.0.8.0:Microsoft
		kernel32.dll:Windows NT BASE API Client DLL:6.1.7601.25954 (win7sp1_ldr_escrow.220429-1730):Microsoft Corporation
		lwjgl.dll
		lwjgl_opengl.dll
		lwjgl_stb.dll
		management.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		mdnsNSP.dll:Bonjour Namespace Provider:3,1,0,1:Apple Inc.
		mscms.dll:Microsoft Color Matching System DLL:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.7601.23403 (win7sp1_ldr.160325-0600):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		ncrypt.dll:Windows cryptographic library:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		ntdll.dll:NT Layer DLL:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		ntmarta.dll:Windows NT MARTA provider:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		ole32.dll:Microsoft OLE for Windows:6.1.7601.25982 (win7sp1_ldr_escrow.220531-1625):Microsoft Corporation
		opengl32.dll:OpenGL Client DLL:6.1.7601.23403 (win7sp1_ldr.160325-0600):Microsoft Corporation
		opus4j.dll
		pnrpnsp.dll:PNRP Name Space Provider:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		profapi.dll:User Profile Basic API:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:6.1.7601.25623 (win7sp1_ldr.210503-1700):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		ucrtbase.DLL:Microsoft® C Runtime Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		uxtheme.dll:Microsoft UxTheme Library:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		webio.dll:Web Transfer Protocols API:6.1.7601.17514 (win7sp1_rtm.101119-1850):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:6.1.7601.17514 (win7sp1_rtm.101119-1850):Microsoft Corporation
		wship6.dll:Winsock2 Helper DLL (TL/IPv6):6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		wshtcpip.dll:Winsock2 Helper DLL (TL/IPv4):6.1.7600.16385 (win7_rtm.090713-1255):Microsoft Corporation
		xinput1_4.dll:Microsoft Common Controller API:9.18.944.0000:Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 425443640 bytes (405 MiB) / 637534208 bytes (608 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 2
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Celeron(R) CPU  N2840  @ 2.16GHz
	Identifier: Intel64 Family 6 Model 55 Stepping 8
	Microarchitecture: Silvermont
	Frequency (GHz): 2.17
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: Intel(R) HD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 774.68
	Graphics card #0 deviceId: 0x0f31
	Graphics card #0 versionInfo: DriverVersion=10.18.10.5161
	Memory slot #0 capacity (MB): 2048.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: Unknown
	Virtual memory max (MB): 9051.36
	Virtual memory used (MB): 1887.90
	Swap memory total (MB): 7118.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		architectury: Architectury 11.1.13
		chatshot: ChatShot 1.0.0
		citresewn: CIT Resewn 1.1.3+1.20
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.20
		cloth-config: Cloth Config v13 13.0.121
			cloth-basic-math: cloth-basic-math 0.6.1
		fabric-api: Fabric API 0.96.4+1.20.4
			fabric-api-base: Fabric API Base 0.4.36+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.49+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.16+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.16+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.4+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.46+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.7+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.41+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.20+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.58+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.86+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.14+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.10+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.23+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.3+b90db5744f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.3+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.61+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.1+09fc25014f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.1+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.74+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.46+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.2.0+d6f2b0844f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.25+58f8c0124f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.41+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.39+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.0+a67ffb5d4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.8+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.5+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.64+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.8+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.7+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.7+2e5ac5484f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.13+080016e44f
			fabric-particles-v1: Fabric Particles (v1) 1.1.7+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.20+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.19+58f8c0124f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.4+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.4+78d798af4f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.53+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.42+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.1+e761c6694f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.56+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.2.0+6fd945a04f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.14+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.19+58f8c0124f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.17+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.55+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.17+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.11+e84342304f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.14+78d798af4f
		fabric-language-kotlin: Fabric Language Kotlin 1.10.18+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		java: OpenJDK 64-Bit Server VM 17
		lithium: Lithium 0.12.1
		minecraft: Minecraft 1.20.4
		modmenu: Mod Menu 9.0.0
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.20.4-build.102
		roughlyenoughitems: Roughly Enough Items 14.0.688
			error_notifier: Error Notifier 1.0.9
		skyblocker: Skyblocker 1.18.1+1.20.4
			com_logisticscraft_occlusionculling: occlusionculling 0.0.7-SNAPSHOT
			meteordevelopment_discord-ipc: discord-ipc 1.1
			moe_nea_neurepoparser: neurepoparser 1.4.0
			org_apache_commons_commons-math3: commons-math3 3.6.1
			org_eclipse_jgit_org_eclipse_jgit: org.eclipse.jgit 6.8.0.202311291450-r
			yet_another_config_lib_v3: YetAnotherConfigLib 3.3.2+1.20.4
				com_twelvemonkeys_common_common-image: common-image 3.10.0
				com_twelvemonkeys_common_common-io: common-io 3.10.0
				com_twelvemonkeys_common_common-lang: common-lang 3.10.0
				com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
				com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
				com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
				org_quiltmc_parsers_gson: gson 0.2.1
				org_quiltmc_parsers_json: json 0.2.1
		sodium: Sodium 0.5.8+mc1.20.4
		starlight: Starlight 1.1.3+fabric.f5dcd1a
		tooltipscroll: Tooltip Scroll 1.3.0
		voicechat: Simple Voice Chat 1.20.4-2.5.7
	Launched Version: fabric-loader-0.15.7-1.20.4
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Intel(R) HD Graphics GL version 3.2.0 - Build 10.18.10.5161, Intel
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_US
	CPU: 2x Intel(R) Celeron(R) CPU N2840 @ 2.16GHz
```

### Additional context

i removed the forceload mod now im getting new crash

**Comment by AzureAaron** [comment]
The version of CIT Resewn you're using is outdated and doesn't support 1.20.4, unfortunately the author has not released a new version so you may have to wait for one :(
