### ISSUE TITLE
Claiming ah ("focusedSlot" is null)

### ISSUE THREAD

**Issue by Mininoob46** [SkyblockerMod/Skyblocker#759]
### Minecraft Version

1.20.6

### Skyblocker Version

skyblocker-1.20.2-beta-ebd5ccd+1.20.6

### Reproduction Steps

1. /ah
2. claim a item
3. crash

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-06-12 15:47:15
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1735.method_7677()" because "focusedSlot" is null
	at de.hysky.skyblocker.skyblock.item.tooltip.adders.NpcPriceTooltip.addToTooltip(NpcPriceTooltip.java:20)
	at de.hysky.skyblocker.skyblock.item.tooltip.TooltipManager.addToTooltip(TooltipManager.java:68)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.modifyReturnValue$bbe000$skyblocker$tooltips$addToTooltip(HandledScreen.java:1385)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.getTooltipFromItem(HandledScreen.java:187)
	at de.hysky.skyblocker.skyblock.auction.AuctionViewScreen.method_2380(AuctionViewScreen.java:192)
	at de.hysky.skyblocker.skyblock.auction.AuctionViewScreen.method_25394(AuctionViewScreen.java:185)
	at net.minecraft.client.gui.screen.Screen.renderWithTooltip(Screen.java:120)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$186(class_757.java)
	at net.minecraft.client.render.GameRenderer.wrapOperation$znj000$fabric-screen-api-v1$onRenderScreen(GameRenderer.java:2101)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:922)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1320)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at de.hysky.skyblocker.skyblock.item.tooltip.adders.NpcPriceTooltip.addToTooltip(NpcPriceTooltip.java:20)
	at de.hysky.skyblocker.skyblock.item.tooltip.TooltipManager.addToTooltip(TooltipManager.java:68)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.modifyReturnValue$bbe000$skyblocker$tooltips$addToTooltip(HandledScreen.java:1385)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.getTooltipFromItem(HandledScreen.java:187)
	at de.hysky.skyblocker.skyblock.auction.AuctionViewScreen.method_2380(AuctionViewScreen.java:192)
	at de.hysky.skyblocker.skyblock.auction.AuctionViewScreen.method_25394(AuctionViewScreen.java:185)
	at net.minecraft.client.gui.screen.Screen.renderWithTooltip(Screen.java:120)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$186(class_757.java)
	at net.minecraft.client.render.GameRenderer.wrapOperation$znj000$fabric-screen-api-v1$onRenderScreen(GameRenderer.java:2101)

-- Screen render details --
Details:
	Screen name: de.hysky.skyblocker.skyblock.auction.AuctionViewScreen
	Mouse location: Scaled: (470, 201). Absolute: (941.000000, 402.000000)
	Screen size: Scaled: (960, 523). Absolute: (1920, 1046). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:922)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1320)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Uptime --
Details:
	JVM uptime: 77.270s
	Wall uptime: 59.330s
	High-res time: 52.693s
	Client ticks: 588 ticks / 29.400s
Stacktrace:
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2548)
	at net.minecraft.client.MinecraftClient.printCrashReport(MinecraftClient.java:983)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:908)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Affected level --
Details:
	All players: 14 total; [class_746['Mininoob46'/420815, l='ClientLevel', x=-513.31, y=101.00, z=-269.37], class_745['DepressingPlayz_'/271424, l='ClientLevel', x=-529.53, y=38.00, z=-232.50], class_745['Huzuni2'/330382, l='ClientLevel', x=-555.72, y=2.22, z=-248.97], class_745['GhstAce'/420822, l='ClientLevel', x=-513.31, y=113.85, z=-269.38], class_745['Todi65'/352101, l='ClientLevel', x=-550.31, y=18.00, z=-264.91], class_745['Chu13'/415217, l='ClientLevel', x=-588.16, y=26.00, z=-325.75], class_745['Persik288'/420971, l='ClientLevel', x=-609.31, y=22.00, z=-274.50], class_745['xpimg678ac'/7, l='ClientLevel', x=-494.50, y=121.00, z=-241.50], class_745['ov8i83fb9i'/75, l='ClientLevel', x=-504.50, y=101.00, z=-284.50], class_745['dima_ybivator228'/304812, l='ClientLevel', x=-623.97, y=15.00, z=-277.56], class_745['Fabi_0802'/313540, l='ClientLevel', x=-626.47, y=19.31, z=-276.84], class_745['TriosFishy'/381913, l='ClientLevel', x=-619.97, y=18.61, z=-280.91], class_745['barata228'/332588, l='ClientLevel', x=-533.37, y=102.27, z=-274.06], class_745['Jonatrok'/422550, l='ClientLevel', x=-503.00, y=101.00, z=-275.00]]
	Chunk stats: 5041, 225
	Level dimension: minecraft:overworld
	Level spawn location: World: (-503,101,-275), Section: (at 9,5,13 in -32,6,-18; chunk contains blocks -512,0,-288 to -497,255,-273), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 849506188 game time, 680020 day time
	Server brand: Hypixel BungeeCord (2024.6.5.2) <- vanilla
	Server type: Non-integrated multiplayer server
	Tracked entity count: 464

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, bbsentials, chat-binds, chatcalc, chatpatches, cloth-config, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, gammautils, hypixel-mod-api, ias, immediatelyfast, modmenu, org_apache_commons_commons-math3, skyblocker, skyblockmod, skylper, yet_another_config_lib_v3, zoomify

-- System Details --
Details:
	Minecraft Version: 1.20.6
	Minecraft Version ID: 1.20.6
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 760215552 bytes (724 MiB) / 2057306112 bytes (1962 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		bbsentials: BBsentials **.**.**.**
			clientarguments: clientarguments 1.8.2
			club_minnced_opus-java: opus-java 1.1.1
			club_minnced_opus-java-api: opus-java-api 1.1.1
			club_minnced_opus-java-natives: opus-java-natives 1.1.1
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.16.0
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.16.0
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.16.0
			com_github_jncrmx_discord-game-sdk4j: discord-game-sdk4j 0.5.5
			com_neovisionaries_nv-websocket-client: nv-websocket-client 2.14
			com_squareup_okhttp3_okhttp: okhttp 4.12.0
			com_squareup_okio_okio-jvm: okio-jvm 3.6.0
			javazoom_jlayer: jlayer 1.0.1
			me_nullicorn_nedit: Nedit 2.2.0
			net_dv8tion_jda: JDA 5.0.0-beta.23
			net_hypixel_mod-api: mod-api 0.4.0
			net_java_dev_jna_jna: jna 4.4.0
			net_sf_trove4j_core: core 3.1.0
			org_apache_commons_commons-collections4: commons-collections4 4.4
			org_jetbrains_annotations: annotations 13.0
			org_jetbrains_kotlin_kotlin-stdlib-common: kotlin-stdlib-common 1.9.10
			org_slf4j_slf4j-api: slf4j-api 1.7.36
		chat-binds: Chat Binds 1.0.0
		chatcalc: ChatCalc 4.0.0
		chatpatches: Chat Patches 206.6.5
		cloth-config: Cloth Config v14 14.0.126
			cloth-basic-math: cloth-basic-math 0.6.1
		entityculling: EntityCulling 1.6.5
		fabric-api: Fabric API 0.100.0 1.20.6
			fabric-api-base: Fabric API Base 0.4.40 80f8cf51b0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.59 e9d2a72bb0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.25 be5d88beb0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.20 6dfe4c9bb0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.8 80f8cf51b0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.50 80f8cf51b0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.12 7f945d5bb0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.45 f71b366fb0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.24 80f8cf51b0
			fabric-commands-v0: Fabric Commands (v0) 0.2.62 df3654b3b0
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.5 b82b2392b0
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.6 7f945d5bb0
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.1.2 bd772e83b0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.27 80f8cf51b0
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.16 2a2c66b6b0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 19.2.2 a5d5299db0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.68 94793913b0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.8 e9d2a72bb0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.6 c5fc38b3b0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.50 80f8cf51b0
			fabric-item-api-v1: Fabric Item API (v1) 8.2.3 6e5bbc4ab0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.0 e0fdb017b0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.45 80f8cf51b0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.43 df3654b3b0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.4 c5fc38b3b0
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.5 97f703dab0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.11 a7dc0e41b0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.12 80f8cf51b0
			fabric-models-v0: Fabric Models (v0) 0.4.11 9386d8a7b0
			fabric-networking-api-v1: Fabric Networking API (v1) 4.1.0 3cb1a7b8b0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.4 c5fc38b3b0
			fabric-particles-v1: Fabric Particles (v1) 4.0.0 c5fc38b3b0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.4 c5fc38b3b0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.17 ad474493b0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.12 97f703dab0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.13 8d125e3bb0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.61 df3654b3b0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.46 73761d2eb0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.3 2c869dedb0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.64 df3654b3b0
			fabric-rendering-v1: Fabric Rendering (v1) 4.2.4 b21c00cbb0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.0 a5d5299db0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.0 c0e5481fb0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.21 7b70ea8ab0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.74 8c7b71c2b0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.21 c5fc38b3b0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.6 c5fc38b3b0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.10 74e2f560b0
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0 kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		gammautils: Gamma Utils 1.8.20
		hypixel-mod-api: Hypixel Mod API 0.4.0 mc1.20.5
		ias: In-Game Account Switcher 9.0.0-beta.5
		immediatelyfast: ImmediatelyFast 1.2.17 1.20.6
			net_lenni0451_reflect: Reflect 1.3.3
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.20.6
		modmenu: Mod Menu 10.0.0-beta.1
		skyblocker: Skyblocker 1.20.2-beta-ebd5ccd 1.20.6
			com_logisticscraft_occlusionculling: occlusionculling 0.0.8-SNAPSHOT
			meteordevelopment_discord-ipc: discord-ipc 1.1
			moe_nea_neurepoparser: neurepoparser 1.5.0
			org_eclipse_jgit_org_eclipse_jgit: org.eclipse.jgit 6.9.0.202403050737-r
		skyblockmod: Skyblock Mod 1.10.3 1.20.6
			org_apache_commons_commons-math3: commons-math3 3.6.1
		skylper: skylper 1.0.0-beta21-1.20.6
			dev_nyon_konfig: konfig 2.0.1-1.20.4
			io_ktor_ktor-client-cio-jvm: ktor-client-cio-jvm 2.3.11
			io_ktor_ktor-client-content-negotiation-jvm: ktor-client-content-negotiation-jvm 2.3.11
			io_ktor_ktor-client-core-jvm: ktor-client-core-jvm 2.3.11
			io_ktor_ktor-events-jvm: ktor-events-jvm 2.3.11
			io_ktor_ktor-http-cio-jvm: ktor-http-cio-jvm 2.3.11
			io_ktor_ktor-http-jvm: ktor-http-jvm 2.3.11
			io_ktor_ktor-io-jvm: ktor-io-jvm 2.3.11
			io_ktor_ktor-network-jvm: ktor-network-jvm 2.3.11
			io_ktor_ktor-network-tls-jvm: ktor-network-tls-jvm 2.3.11
			io_ktor_ktor-serialization-jvm: ktor-serialization-jvm 2.3.11
			io_ktor_ktor-serialization-kotlinx-json-jvm: ktor-serialization-kotlinx-json-jvm 2.3.11
			io_ktor_ktor-serialization-kotlinx-jvm: ktor-serialization-kotlinx-jvm 2.3.11
			io_ktor_ktor-utils-jvm: ktor-utils-jvm 2.3.11
			io_ktor_ktor-websocket-serialization-jvm: ktor-websocket-serialization-jvm 2.3.11
			io_ktor_ktor-websockets-jvm: ktor-websockets-jvm 2.3.11
		yet_another_config_lib_v3: YetAnotherConfigLib 3.4.4 1.20.6-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		zoomify: Zoomify 2.13.5 1.20.6
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.1
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
	Launched Version: 1.20.6
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: AMD Radeon(TM) Graphics GL version 3.2.0 Core Profile Context **.**.**.**.230913, ATI Technologies Inc.
	Window size: 1920x1046
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fast
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, bbsentials, chat-binds, chatcalc, chatpatches, cloth-config, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, gammautils, hypixel-mod-api, ias, immediatelyfast, modmenu, org_apache_commons_commons-math3, skyblocker, skyblockmod, skylper, yet_another_config_lib_v3 (incompatible), zoomify
	Current Language: en_us
	Locale: en_NO
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# C:\Games\PrismLauncher\instances\1.20.6\.minecraft\crash-reports\crash-2024-06-12_15.47.15-client.txt
Process exited with code -1.
```

### Additional context

https://mclo.gs/4gIeJH4

**Comment by kevinthegreat1** [comment]
Fixed in #750. You can get that build [here](https://github.com/SkyblockerMod/Skyblocker/actions/runs/9468594781) or bleeding edge [here](https://nightly.link/SkyblockerMod/Skyblocker/workflows/beta/bleeding-edge).
