### ISSUE TITLE
Game crashes when leaving server

### ISSUE THREAD

**Issue by wombat24455** [SkyblockerMod/Skyblocker#77]
# Issue
When I leave Hypixel the game crashes

## Version
I am using skyblocker v1.8.0 for Fabric 1.18.2

## Crash message
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_634.method_2880()" because the return value of "net.minecraft.class_310.method_1562()" is null
	at me.xmrvizzy.skyblocker.skyblock.BackpackPreview.getSkyblockProfile(BackpackPreview.java:171)
	at me.xmrvizzy.skyblocker.skyblock.BackpackPreview.tick(BackpackPreview.java:49)
	at me.xmrvizzy.skyblocker.utils.Scheduler$CyclicTask.run(Scheduler.java:53)
	at me.xmrvizzy.skyblocker.utils.Scheduler$ScheduledTask.run(Scheduler.java:65)
	at me.xmrvizzy.skyblocker.utils.Scheduler.tick(Scheduler.java:37)
	at me.xmrvizzy.skyblocker.SkyblockerMod.onTick(SkyblockerMod.java:32)
	at net.minecraft.class_310.handler$bkd001$tick(class_310.java:13456)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1091)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by wombat24455** [comment]
Realised this issue is a duplicate of some previous issues, using the beta build seemed to fix the issue.
