### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by XcusanaIi** [SkyblockerMod/Skyblocker#799]
### Minecraft Version

1.21.0

### Skyblocker Version

skyblocker-1.21.0+1.20.6

### Reproduction Steps

Just a random NullPointerException crash

### Crash Report file and latest.log

```shell
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapIterator.nextEntry(Object2ObjectOpenHashMap.java:637) ~[fastutil-8.5.12.jar:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$EntryIterator.next(Object2ObjectOpenHashMap.java:731) ~[fastutil-8.5.12.jar:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$EntryIterator.next(Object2ObjectOpenHashMap.java:726) ~[fastutil-8.5.12.jar:?]
	at de.hysky.skyblocker.skyblock.events.EventNotifications.timeUpdate(EventNotifications.java:131) ~[skyblocker-1.21.0+1.20.6.jar:?]
	at de.hysky.skyblocker.utils.scheduler.Scheduler$ScheduledTask.run(Scheduler.java:142) ~[skyblocker-1.21.0+1.20.6.jar:?]
	at de.hysky.skyblocker.utils.scheduler.Scheduler.runTask(Scheduler.java:116) ~[skyblocker-1.21.0+1.20.6.jar:?]
	at de.hysky.skyblocker.utils.scheduler.Scheduler.tick(Scheduler.java:97) ~[skyblocker-1.21.0+1.20.6.jar:?]
	at de.hysky.skyblocker.SkyblockerMod.tick(SkyblockerMod.java:211) ~[skyblocker-1.21.0+1.20.6.jar:?]
```

**Comment by viciscat** [comment]
Did it crash not long after joining skyblock?

**Comment by viciscat** [comment]
Could you also send the full latest.log file? By uploading it to [mclo.gs](https://mclo.gs)

**Comment by XcusanaIi** [comment]
> Did it crash not long after joining skyblock?

I played for hrs and when i walking in a dungeon room it crashed

**Comment by XcusanaIi** [comment]
> Could you also send the full latest.log file? By uploading it to [mclo.gs](https://mclo.gs) and sending the link here

Sry i'm not willing to upload it

**Comment by viciscat** [comment]
> Sry i'm not willing to upload it

why not?

**Comment by kevinthegreat1** [comment]
Is it just username? mclo.gs hides it: https://aternos.gmbh/en/mclogs/privacy. Otherwise you gave us very little information to debug and we can't fix this.

**Comment by XcusanaIi** [comment]
The latest.log: https://mclo.gs/qFHVpk3

**Comment by LifeIsAParadox** [comment]
I have not been able to reproduce this bug. It looks like an edge case. If the bug happens again, could you send your latest.log again and also tell us what you were doing before the crash happened.

**Comment by kevinthegreat1** [comment]
@LifeIsAParadox We figured it out. https://github.com/SkyblockerMod/Skyblocker/blob/9a59ee74d4e61aa2d31076a587fbf9ed2d6c6a64/src/main/java/de/hysky/skyblocker/skyblock/events/EventNotifications.java#L88 needs to be changed to a `ConcurrentHashMap`. While we’re at it, https://github.com/SkyblockerMod/Skyblocker/blob/9a59ee74d4e61aa2d31076a587fbf9ed2d6c6a64/src/main/java/de/hysky/skyblocker/skyblock/events/EventNotifications.java#L42 should also be changed to a `Map.of`.
