### ISSUE TITLE
Bug with Museum if you try to click in NPC.

### ISSUE THREAD

**Issue by xAli0yx** [SkyblockerMod/Skyblocker#807]
### Minecraft Version

1.21.0

### Skyblocker Version

skyblocker-1.21.0+1.21.jar

### Reproduction Steps

1. Go to HUB.
2. Walk to the Museum.
3. Talk the NPC.
4. Try to click them your armor or weapon.

Watch here: https://youtu.be/jVDwbEC3X5M

### Crash Report file and latest.log

```shell
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2024-06-28 09:56:26
Description: mouseClicked event handler

java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectOpenHashSet.add(Object)" because the return value of "de.hysky.skyblocker.skyblock.item.MuseumItemCache$ProfileMuseumData.collectedItemIds()" is null
	at de.hysky.skyblocker.skyblock.item.MuseumItemCache.handleClick(MuseumItemCache.java:118)
	at net.minecraft.class_465.handler$cdm000$skyblocker$onSlotClick(class_465.java:2461)
	at net.minecraft.class_465.method_2383(class_465.java:557)
	at net.minecraft.class_465.method_25402(class_465.java:349)
	at net.minecraft.class_312.method_1611(class_312.java:107)
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:107)
	at net.minecraft.class_312.method_22686(class_312.java:196)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:196)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168)
	at net.minecraft.class_1041.method_15998(class_1041.java:303)
	at net.minecraft.class_310.method_1523(class_310.java:1307)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at de.hysky.skyblocker.skyblock.item.MuseumItemCache.handleClick(MuseumItemCache.java:118)
	at net.minecraft.class_465.handler$cdm000$skyblocker$onSlotClick(class_465.java:2461)
	at net.minecraft.class_465.method_2383(class_465.java:557)
	at net.minecraft.class_465.method_25402(class_465.java:349)
	at net.minecraft.class_312.method_1611(class_312.java:107)
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:107)
	at net.minecraft.class_312.method_22686(class_312.java:196)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:196)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_476
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:107)
	at net.minecraft.class_312.method_22686(class_312.java:196)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:196)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168)
	at net.minecraft.class_1041.method_15998(class_1041.java:303)
	at net.minecraft.class_310.method_1523(class_310.java:1307)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 109.036s
	Wall uptime: 88.129s
	High-res time: 83.972s
	Client ticks: 1434 ticks / 71.700s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:902)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 9 total; [class_746['xAli0yx_Deaf'/334248, l='ClientLevel', x=-63.06, y=77.00, z=83.40], class_745['Mxnokuma'/334249, l='ClientLevel', x=-63.06, y=88.83, z=83.38], class_745['Tellercrafter'/333602, l='ClientLevel', x=-108.59, y=74.00, z=57.13], class_745['Aishe_'/324000, l='ClientLevel', x=-62.06, y=76.00, z=82.56], class_745['ck2e9u4742'/512, l='ClientLevel', x=-62.50, y=77.00, z=84.50], class_745['6wsw1hgoc7'/513, l='ClientLevel', x=-49.50, y=77.00, z=76.50], class_745['Poussin51'/334142, l='ClientLevel', x=-26.53, y=94.00, z=8.50], class_745['krembo99'/335266, l='ClientLevel', x=-40.93, y=85.39, z=-4.71], class_745['Jamarah'/335274, l='ClientLevel', x=-43.55, y=87.61, z=4.84]]
	Chunk stats: 16384, 225
	Level dimension: minecraft:overworld
	Level spawn location: World: (-3,70,-70), Section: (at 13,6,10 in -1,4,-5; chunk contains blocks -16,0,-80 to -1,255,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 849464778 game time, 667739 day time
	Server brand: Hypixel BungeeCord (2024.6.27.1) <- vanilla
	Server type: Non-integrated multiplayer server
	Tracked entity count: 376

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, caffeineconfig, controlify, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, immediatelyfast, indium, iris, lithium, modmenu, org_apache_commons_commons-math3, reeses-sodium-options, skyblocker, sodium, sodium-extra, yet_another_config_lib_v3

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 318781704 bytes (304 MiB) / 1140850688 bytes (1088 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 1.99
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics 620
	Graphics card #0 vendor: Intel Corporation
	Graphics card #0 VRAM (MiB): 1024.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.101.2127
	Graphics card #1 name: NVIDIA GeForce MX130
	Graphics card #1 vendor: NVIDIA
	Graphics card #1 VRAM (MiB): 2048.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 32.0.15.5599
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Virtual memory max (MiB): 12422.87
	Virtual memory used (MiB): 10887.55
	Swap memory total (MiB): 4352.00
	Swap memory used (MiB): 405.36
	Space in storage for jna.tmpdir (MiB): available: 107093.20, total: 243303.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 107093.20, total: 243303.00
	Space in storage for io.netty.native.workdir (MiB): available: 107093.20, total: 243303.00
	Space in storage for java.io.tmpdir (MiB): available: 107093.20, total: 243303.00
	Space in storage for workdir (MiB): available: 107093.20, total: 243303.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		controlify: Controlify 2.0.0-beta.13+1.21-fabric
			dev_isxander_libsdl4j: libsdl4j 3.6896c4c-38
			org_hid4java_hid4java: hid4java 0.7.0
			org_quiltmc_parsers_gson: gson 0.3.0
			org_quiltmc_parsers_json: json 0.3.0
		entityculling: EntityCulling 1.6.6
		fabric-api: Fabric API 0.100.3+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.28+6fc22b99d1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.48+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.27+6a6dfa19d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.65+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.13+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.14+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.3.1+8a3b5617d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.23+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.8+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f883d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.52+6573ed8cd1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.1+cb5ced13d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.10+6573ed8cd1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.11+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.9+6573ed8cd1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.22+ab7edbacd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.16+fe474d6bd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.4+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.66+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.69+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.3+d1321076d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.4+cb5ced13d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.79+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.14+b5597344d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		ferritecore: FerriteCore 7.0.0
		immediatelyfast: ImmediatelyFast 1.2.18+1.21
			net_lenni0451_reflect: Reflect 1.3.4
		indium: Indium 1.0.33+mc1.21
		iris: Iris 1.7.1+mc1.21
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		lithium: Lithium 0.12.7
		minecraft: Minecraft 1.21
		modmenu: Mod Menu 11.0.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.21
		skyblocker: Skyblocker 1.21.0+1.21
			com_logisticscraft_occlusionculling: occlusionculling 0.0.8-SNAPSHOT
			meteordevelopment_discord-ipc: discord-ipc 1.1
			moe_nea_neurepoparser: neurepoparser 1.5.0
			org_apache_commons_commons-math3: commons-math3 3.6.1
			org_eclipse_jgit_org_eclipse_jgit: org.eclipse.jgit 6.9.0.202403050737-r
		sodium: Sodium 0.5.9+mc1.21
		sodium-extra: Sodium Extra 0.5.7+mc1.21
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.15.11-1.21
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce MX130/PCIe/SSE2 GL version 3.2.0 NVIDIA 555.99, NVIDIA Corporation
	Window size: 1366x768
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 8/8 chunks
	Resource Packs: vanilla, fabric, caffeineconfig, controlify, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, immediatelyfast, indium, iris, lithium, modmenu, org_apache_commons_commons-math3, reeses-sodium-options, skyblocker, sodium, sodium-extra, yet_another_config_lib_v3 (incompatible)
	Current Language: en_us
	Locale: pt_PT
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 8x Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
```

**Comment by LifeIsAParadox** [comment]
This bug got fixed in latest master.
Could you try **[this](https://nightly.link/SkyblockerMod/Skyblocker/actions/runs/9687022604/skyblocker-1.21.0-beta-9a59ee7%2B1.21.zip)** version and tell me if this works for you. If it works i will release a new version on modrinth.

**Comment by xAli0yx** [comment]
> This bug got fixed in latest master. Could you try **[this](https://nightly.link/SkyblockerMod/Skyblocker/actions/runs/9687022604/skyblocker-1.21.0-beta-9a59ee7%2B1.21.zip)** version and tell me if this works for you. If it works i will release a new version on modrinth.

Your updatest mod has been fixed by I am testing as done!
