### ISSUE TITLE
Failed to get Player Profile Data

### ISSUE THREAD

**Issue by Reddishye** [SkyblockerMod/Skyblocker#850]
### Minecraft Version

1.21.0

### Skyblocker Version

skyblocker-1.21.1+1.20.6.jar

### Reproduction Steps

start the game for 1.20.6 lol

### Crash Report file and latest.log

```shell
at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
[21:58:22] [main/WARN]:
 Error loading class: me/jellysquid/mods/sodium/client/world/biome/BlockColorCache (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/world/biome/BlockColorCache)
[21:58:22] [main/WARN]:
 Error loading class: dev/tr7zw/skinlayers/render/CustomizableModelPart (java.lang.ClassNotFoundException: dev/tr7zw/skinlayers/render/CustomizableModelPart)
[21:58:22] [main/WARN]:
 Force-disabling mixin 'features.render.entity.shadows.EntityRenderDispatcherMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[21:58:22] [main/WARN]:
 Force-disabling mixin 'features.render.gui.font.GlyphRendererMixin' as rule 'mixin.features.render.gui.font' (added by mods [iris]) disables it and children
[21:58:29] [Datafixer Bootstrap/INFO]:
 222 Datafixer optimizations took 217 milliseconds
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$createVisibles$33(Lnet/minecraft/class_338;Ljava/util/List;Lnet/minecraft/class_303;)V to mdf9fa10$chatpatches$lambda$createVisibles$33$8 in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$loadCopyMenu$30(Lobro1961/chatpatches/gui/MenuButtonWidget;)Z to mdf9fa10$chatpatches$lambda$loadCopyMenu$30$b in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$loadCopyMenu$29(Lobro1961/chatpatches/gui/MenuButtonWidget;)Z to mdf9fa10$chatpatches$lambda$loadCopyMenu$29$c in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$loadCopyMenu$28(Lobro1961/chatpatches/gui/MenuButtonWidget;)V to mdf9fa10$chatpatches$lambda$loadCopyMenu$28$d in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$loadCopyMenu$27(Ljava/lang/String;)Ljava/lang/String; to mdf9fa10$chatpatches$lambda$loadCopyMenu$27$e in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$loadCopyMenu$26(Ljava/lang/String;Lnet/minecraft/class_303;)Z to mdf9fa10$chatpatches$lambda$loadCopyMenu$26$f in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$isMouseOverCopyMenu$25(DDLobro1961/chatpatches/gui/MenuButtonWidget;)Z to mdf9fa10$chatpatches$lambda$isMouseOverCopyMenu$25$10 in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$mouseMoved$24(DDLobro1961/chatpatches/gui/MenuButtonWidget;)V to mdf9fa10$chatpatches$lambda$mouseMoved$24$11 in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$afterClickBtn$22(DDILobro1961/chatpatches/gui/MenuButtonWidget;)Z to mdf9fa10$chatpatches$lambda$afterClickBtn$22$13 in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$afterClickBtn$21(DDILobro1961/chatpatches/gui/MenuButtonWidget;)Z to mdf9fa10$chatpatches$lambda$afterClickBtn$21$14 in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$renderSearchStuff$20(Lnet/minecraft/class_332;IIFLobro1961/chatpatches/gui/MenuButtonWidget;)V to mdf9fa10$chatpatches$lambda$renderSearchStuff$20$15 in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$renderSearchStuff$19(Lnet/minecraft/class_332;IIFLobro1961/chatpatches/gui/MenuButtonWidget;)V to mdf9fa10$chatpatches$lambda$renderSearchStuff$19$16 in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$renderSearchStuff$18(Lnet/minecraft/class_332;IIFLobro1961/chatpatches/gui/MenuButtonWidget;)V to mdf9fa10$chatpatches$lambda$renderSearchStuff$18$17 in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$initSearchStuff$17(Lobro1961/chatpatches/gui/MenuButtonWidget;)V to mdf9fa10$chatpatches$lambda$initSearchStuff$17$18 in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$initSearchStuff$16(ILobro1961/chatpatches/gui/MenuButtonWidget;)V to mdf9fa10$chatpatches$lambda$initSearchStuff$16$19 in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$initSearchStuff$15(Lobro1961/chatpatches/gui/MenuButtonWidget;)I to mdf9fa10$chatpatches$lambda$initSearchStuff$15$1a in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$initSearchStuff$14(Lobro1961/chatpatches/gui/MenuButtonWidget;)V to mdf9fa10$chatpatches$lambda$initSearchStuff$14$1b in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$initSearchStuff$11()Ljava/lang/String; to mdf9fa10$chatpatches$lambda$initSearchStuff$11$1e in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$initSearchStuff$10()Ljava/lang/String; to mdf9fa10$chatpatches$lambda$initSearchStuff$10$1f in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$initSearchStuff$9()Ljava/lang/String; to mdf9fa10$chatpatches$lambda$initSearchStuff$9$20 in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$initSearchStuff$8()Ljava/lang/String; to mdf9fa10$chatpatches$lambda$initSearchStuff$8$21 in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$initSearchStuff$7()Ljava/lang/String; to mdf9fa10$chatpatches$lambda$initSearchStuff$7$22 in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$initSearchStuff$6()Ljava/lang/String; to mdf9fa10$chatpatches$lambda$initSearchStuff$6$23 in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$initSearchStuff$2(Lnet/minecraft/class_4185;)V to mdf9fa10$chatpatches$lambda$initSearchStuff$2$27 in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$initSearchStuff$1(Lnet/minecraft/class_4185;)V to mdf9fa10$chatpatches$lambda$initSearchStuff$1$28 in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Renaming synthetic method lambda$static$0(Ljava/lang/Integer;)Lnet/minecraft/class_2561; to mdf9fa10$chatpatches$lambda$static$0$29 in chatpatches.mixins.json:gui.ChatScreenMixin from mod chatpatches
[21:58:31] [Render thread/INFO]:
 Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[21:58:31] [Render thread/INFO]:
 Setting user: {MINECRAFT_USERNAME}
[21:58:31] [Render thread/INFO]:
 Loading Collective version 7.71.
[21:58:31] [Render thread/INFO]:
 Successfully Debugify'd your game!
[21:58:32] [Render thread/INFO]:
 Config values:
Hotbar speed: 0.2
Chat speed: 0.5
Chat Opening speed: 0.5
Entry list speed: 0.5
Mask debug enabled: false
Config version: 2.1
[21:58:32] [Via-Mappingloader-0/INFO]:
 Loading block connection mappings ...
[21:58:32] [Via-Mappingloader-0/INFO]:
 Using FastUtil Long2ObjectOpenHashMap for block connections
[21:58:32] [ForkJoinPool.commonPool-worker-1/INFO]:
 Loading translations...
[21:58:32] [ForkJoinPool.commonPool-worker-1/INFO]:
 Registering protocols...
[21:58:33] [Render thread/INFO]:
 Got request to register class com.sk89q.worldedit.fabric.FabricPlatform with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@490af623]
[21:58:33] [Render thread/INFO]:
 WorldEdit for Fabric (version 7.3.3+6788-6359df8) is loaded
[21:58:33] [Render thread/INFO]:
 [BetterF3] Loading...
[21:58:33] [Render thread/INFO]:
 [BetterF3] All done!
[21:58:33] [Render thread/INFO]:
 [Config.read] Loaded config info from 'C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\profiles\NPP_ Quilted\config\chatpatches.json'!
[21:58:33] [Render thread/INFO]:
 [Config.write] Saved config info to 'C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\profiles\NPP_ Quilted\config\chatpatches.json'!
[21:58:33] [Render thread/INFO]:
 Mixing security.CPNHMixin from chatpatches.mixins.json into net.minecraft.class_634
[21:58:33] [Render thread/INFO]:
 [ChatPatches()] Finished setting up!
[21:58:33] [Render thread/WARN]:
 Injection warning: LVT in net/minecraft/class_332::method_51435(Lnet/minecraft/class_327;Ljava/util/List;IILnet/minecraft/class_8000;)V has incompatible changes at opcode 124 in callback iceberg.mixins.json:GuiGraphicsMixin from mod iceberg->@Inject::storeLocalsOptifine(Lnet/minecraft/class_327;Ljava/util/List;IILnet/minecraft/class_8000;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Ljava/lang/Object;IIIILorg/joml/Vector2ic;)V.
 Expected: [Ljava/lang/Object;, I, I, I, I, Lorg/joml/Vector2ic;]
    Found: [I, I, I, I, Lorg/joml/Vector2ic;]
Available: [I, I, I, I, Lorg/joml/Vector2ic;]
[21:58:33] [Render thread/INFO]:
 Loading Entity Model Features, allegedly compatible with the OptiFine format.
[21:58:34] [Render thread/INFO]:
 6 new ETF Random Properties registered by entity_model_features.
[21:58:34] [Render thread/INFO]:
 Loading Entity Texture Features, Thanks for 10 Million plus downloads!!
[21:58:34] [Render thread/INFO]:
 [Indigo] Different rendering plugin detected; not applying Indigo.
[21:58:34] [ForkJoinPool.commonPool-worker-1/INFO]:
 Started resource pack HTTP server on http://127.0.0.1:54878/
[21:58:34] [ForkJoinPool.commonPool-worker-1/INFO]:
 ViaVersion detected lowest supported version by the proxy: c0.0.15a-1 (0)
[21:58:34] [ForkJoinPool.commonPool-worker-1/INFO]:
 Highest supported version by the proxy: 1.21 (767)
[21:58:34] [ForkJoinPool.commonPool-worker-1/INFO]:
 Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[21:58:35] [Render thread/INFO]:
 Checking mod updates...
[21:58:36] [Render thread/INFO]:
 [SkinTypeFix] Loaded!
[21:58:36] [Render thread/INFO]:
 Deserializing SkyblockerConfig from 'C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\profiles\NPP_ Quilted\config\skyblocker.json'
[21:58:36] [Render thread/ERROR]:
 [Skyblocker Waypoints] Encountered exception while loading waypoints
java.nio.file.NoSuchFileException: C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\profiles\NPP_ Quilted\config\skyblocker\waypoints.json
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source) ~[?:?]
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:?]
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:?]
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source) ~[?:?]
	at java.base/java.nio.file.Files.newByteChannel(Unknown Source) ~[?:?]
	at java.base/java.nio.file.Files.newByteChannel(Unknown Source) ~[?:?]
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(Unknown Source) ~[?:?]
	at java.base/java.nio.file.Files.newInputStream(Unknown Source) ~[?:?]
	at java.base/java.nio.file.Files.newBufferedReader(Unknown Source) ~[?:?]
	at java.base/java.nio.file.Files.newBufferedReader(Unknown Source) ~[?:?]
	at de.hysky.skyblocker.skyblock.waypoint.Waypoints.loadWaypoints(Waypoints.java:57) ~[skyblocker-1.21.1+1.20.6.jar:?]
	at de.hysky.skyblocker.skyblock.waypoint.Waypoints.init(Waypoints.java:49) ~[skyblocker-1.21.1+1.20.6.jar:?]
	at de.hysky.skyblocker.SkyblockerMod.onInitializeClient(SkyblockerMod.java:117) ~[skyblocker-1.21.1+1.20.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) [fabric-loader-0.16.0.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:484) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.0.jar:?]
[21:58:36] [ForkJoinPool.commonPool-worker-3/WARN]:
 [Skyblocker] Shortcuts file not found, using default shortcuts. This is normal when using for the first time.
[21:58:36] [ForkJoinPool.commonPool-worker-3/WARN]:
 [Skyblocker Chat Rules] chat rules file not found, using default rules. This is normal when using for the first time.
[21:58:36] [ForkJoinPool.commonPool-worker-2/INFO]:
 [Skyblocker Player Head Hash Cache] Successfully cached the hashes of all player head items!
[21:58:36] [ForkJoinPool.commonPool-worker-3/WARN]:
 [Skyblocker] No status bar config file found, using defaults
[21:58:36] [Render thread/INFO]:
 [Skyblocker Time] Skyblock time updated to Year 361, Season SPRING, Month LATE_SPRING, Day 17
[21:58:36] [ForkJoinPool.commonPool-worker-2/ERROR]:
 [Skyblocker Profile Utils] Failed to get Player Profile Data for players {MINECRAFT_USERNAME}, is the API Down/Limited?
java.lang.IllegalStateException: Failed to get profile uuid for players {MINECRAFT_USERNAME}! Response: <h1>403 Forbidden</h1>
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
[21:58:36] [Render thread/INFO]:
 [SSPB] Broken dirt path lighting is best dirt path lighting lol

[21:58:36] [Render thread/INFO]:
 Deserializing YACLConfig from 'C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\profiles\NPP_ Quilted\config\yacl.json5'
```

**Comment by Reddishye** [comment]
Note: My bad, is not a crash report, just that I saw these errors and I wanted to report them.

**Comment by AzureAaron** [comment]
Recently we changed how our API works and only 1.21+ clients can use it (because it needed changes in the mod), these errors are the result of that and can be ignored unless you use item cooldowns or the player secrets tracker in dungeons. If you need these features then you may want to update your game.
