### ISSUE TITLE
Crash when opening the settings

### ISSUE THREAD

**Issue by AC19970** [SkyblockerMod/Skyblocker#890]
### Minecraft Version

1.21.0

### Skyblocker Version

skyblocker-1.21.1-beta-da041ea+1.21 

### Reproduction Steps

Run the game, open settings, and it crashes.

### Crash Report file and latest.log

```shell
[11:04:04] [Render thread/INFO]:
 Generating YACL screen
[11:04:04] [Render thread/ERROR]:
 Reported exception thrown!
	at net.minecraft.class_312.method_22686(class_312.java:196) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:108) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:196) ~[client-intermediary.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.3.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509) ~[lwjgl-glfw-3.3.3.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:184) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1310) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.0.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "this.inputField" is null
	at dev.isxander.yacl3.gui.controllers.string.StringControllerElement.getValueText(StringControllerElement.java:461) ~[YetAnotherConfigLib-3.5.0+1.21-fabric.jar:?]
	at dev.isxander.yacl3.gui.controllers.string.StringControllerElement.setDimension(StringControllerElement.java:436) ~[YetAnotherConfigLib-3.5.0+1.21-fabric.jar:?]
	at dev.isxander.yacl3.gui.controllers.string.StringControllerElement.<init>(StringControllerElement.java:45) ~[YetAnotherConfigLib-3.5.0+1.21-fabric.jar:?]
	at dev.isxander.yacl3.gui.controllers.string.IStringController.provideWidget(IStringController.java:42) ~[YetAnotherConfigLib-3.5.0+1.21-fabric.jar:?]
	at dev.isxander.yacl3.gui.OptionListWidget.refreshOptions(OptionListWidget.java:75) ~[YetAnotherConfigLib-3.5.0+1.21-fabric.jar:?]
	at dev.isxander.yacl3.gui.OptionListWidget.<init>(OptionListWidget.java:40) ~[YetAnotherConfigLib-3.5.0+1.21-fabric.jar:?]
	at dev.isxander.yacl3.gui.YACLScreen$CategoryTab.<init>(YACLScreen.java:359) ~[YetAnotherConfigLib-3.5.0+1.21-fabric.jar:?]
	at dev.isxander.yacl3.gui.YACLScreen.lambda$init$4(YACLScreen.java:89) ~[YetAnotherConfigLib-3.5.0+1.21-fabric.jar:?]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source) ~[?:?]
	at dev.isxander.yacl3.gui.YACLScreen.method_25426(YACLScreen.java:90) ~[YetAnotherConfigLib-3.5.0+1.21-fabric.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:309) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1143) ~[client-intermediary.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.openConfig(ModListEntry.java:185) ~[modmenu-11.0.1.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.method_25402(ModListEntry.java:175) ~[modmenu-11.0.1.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModListWidget.method_25402(ModListWidget.java:298) ~[modmenu-11.0.1.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:431) ~[client-intermediary.jar:?]
	... 14 more
```

**Comment by kevinthegreat1** [comment]
It seems like your event notification config is messed up. Can you send your `config/skyblocker.json`?

cc: @viciscat

**Comment by Luga2475** [comment]
Minecraft Version
1.21.0

Skyblocker Version
skyblocker-1.21.1-beta-da041ea+1.21

slightly different crash report

[22:14:04] [Render thread/INFO]:
 Generating YACL screen
[22:14:04] [Render thread/ERROR]:
 Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:436) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:196) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:108) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:196) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.3.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.3.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438) ~[lwjgl-glfw-3.3.3.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:303) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1307) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.0.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "this.inputField" is null
	at dev.isxander.yacl3.gui.controllers.string.StringControllerElement.getValueText(StringControllerElement.java:461) ~[yet_another_config_lib_v3-3.5.0+1.21-fabric-bbf2959bd3405562.jar:?]

[skyblocker.json](https://github.com/user-attachments/files/16488853/skyblocker.json)

**Comment by AC19970** [comment]
> It seems like your event notification config is messed up. Can you send your `config/skyblocker.json`?
> 
> cc: @viciscat

My event notification config is basically the same as Luga2475. I removed values of events that are no longer needed, such as Traveling Zoo.

	"eventNotifications": {
		"criterion": "SKYBLOCK",
		"reminderSound": "PLING",
		"eventsReminderTimes": {
			"Election Booth Opens": [
				60,
				300
			],
			"Bonus Mining Fiesta": [
				60,
				300
			],
			"Season of Jerry": [],
			"Hoppity's Hunt Begins": [],
			"Spooky Festival": [
				60,
				300
			],
			"Traveling Zoo": [],
			"New Year Celebration": [
				60,
				300
			],
			"Bonus Fishing Festival": [
				60,
				300
			],
			"Jerry's Workshop Opens": [],
			"Election Over!": [
				60,
				300
			],
			"SkyBlock Anniversary": [
				60,
				300
			],
			"Jacob's Farming Contest": [
				60,
				300
			],
			"Dark Auction": [
				60,
				300
			],
			"Bonus Spooky Festival": [
				60,
				300
			]
		}
	},

**Comment by AC19970** [comment]
btw when opening the settings menu in skyblock, the game does not crash, but the menu has nothing in it except the background.

**Comment by Luga2475** [comment]
yeah when you do /skyblocker config then it is just empty
but if i do /skyblocker and then click on the config button it crashes

**Comment by justino901** [comment]
im having the exact same problem as well ever since updating to the latest github master release

[skyblocker.json](https://github.com/user-attachments/files/16490010/skyblocker.json)
[latest.log](https://github.com/user-attachments/files/16490020/latest.log)
skyblocker version : skyblocker-1.21.1-beta-da041ea+1.21.jar

**Comment by justino901** [comment]
i think the problem might be the difference in the quick nav buttons as when i changed that in my skyblocker.json it seems to have fixed it

**Comment by justino901** [comment]
nevermind now it just wont take my old json that i tried to fix so i just went back through the skyblocker settings to make my old setup again...

**Comment by Luga2475** [comment]
what justino901 tryed worked for me.
copy skyblocker.json somewhere else
close game 
delete skyblocker.json in the config folder
start the game
coppy the ( "tooltip": " ... ", ) from new json to old one for every quick nav button
close game 
delete new skyblocker.json in the config folder
paste old and edited skyblocker.json in the config folder
