### ISSUE TITLE
Chocolate Factory crash on menu open

### ISSUE THREAD

**Issue by physanus** [SkyblockerMod/Skyblocker#915]
### What happened?

The game crashes when opening the chocolate factory via `/cf` whilst having an almost-maxed cf.

### Log output

```
java.lang.NumberFormatException: For input string: "2180329984"
	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at de.hysky.skyblocker.utils.RegexUtils.getIntFromMatcher(RegexUtils.java:36)
	at de.hysky.skyblocker.skyblock.chocolatefactory.ChocolateFactorySolver.getRabbit(ChocolateFactorySolver.java:230)
	at de.hysky.skyblocker.skyblock.chocolatefactory.ChocolateFactorySolver.updateFactoryInfo(ChocolateFactorySolver.java:124)
	at de.hysky.skyblocker.skyblock.chocolatefactory.ChocolateFactorySolver.getColors(ChocolateFactorySolver.java:92)
	at de.hysky.skyblocker.utils.render.gui.ContainerSolverManager.onDraw(ContainerSolverManager.java:136)
	at de.hysky.skyblocker.utils.render.gui.ContainerSolverManager.lambda$init$0(ContainerSolverManager.java:75)
	at net.fabricmc.fabric.impl.client.screen.ScreenEventFactory.lambda$createAfterRenderEvent$4(ScreenEventFactory.java:48)
	at net.minecraft.class_757.wrapOperation$bcg000$fabric-screen-api-v1$onRenderScreen(class_757.java:3087)
	at net.minecraft.class_757.method_3192(class_757.java:913)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

### Minecraft Version

1.21.0

### Skyblocker Version

skyblocker-1.21.1+1.21.jar

**Comment by Julienraptor02** [comment]
Well done 🤣 you caught the integer overflow
@Emirlol should've used a long (i think it's part of the things that i noticed and fixed in my enhanced CF helper)

**Comment by physanus** [comment]
I do have less than 2.147.483.647 Chocolate. I assume it is about the algorithm which finds the best rabbit to upgrade. My Rabbit Dog requires 2.180.329.984 chocolate for upgrading to level 219. 
Also, the first crash happened right after hitting the upgrade from level 217 to 218.

However, this probably fixes itself (on my end) after 2 more rabbit upgrades! (:

**Comment by Julienraptor02** [comment]
> I do have less than 2.147.483.647 Chocolate. I assume it is about the algorithm which finds the best rabbit to upgrade. My Rabbit Dog requires 2.180.329.984 chocolate for upgrading to level 219. Also, the first crash happened right after hitting the upgrade from level 217 to 218.
> 
> However, this probably fixes itself (on my end) after 2 more rabbit upgrades! (:

yeah what i meant is parsing that number is too high, no matter if it's chocolate you have or need, it'll get fixed soon:tm:

**Comment by AzureAaron** [comment]
Are you sure you're using the latest version? I'm pretty sure this was fixed, send your log if you're unsure

**Comment by Julienraptor02** [comment]
this was fixed 2 month ago https://github.com/SkyblockerMod/Skyblocker/commit/bc773c76b3362af799577c89fa6f7b79c1ee013b
HOWEVER, because we update way too slow, the fix isn't even released
currently, the best thing you can do us grab the latest master build...
https://github.com/SkyblockerMod/Skyblocker/actions/runs/10330911744/artifacts/1797747149

**Comment by physanus** [comment]
Makes sense. I used to build it myself from master but recently switched to [a modpack](https://modrinth.com/modpack/skyblocker-modpack) – what a coincidence.
Thank you for your time!
