### ISSUE TITLE
Cannot buy items in auction agent

### ISSUE THREAD

**Issue by T0oKEN** [SkyblockerMod/Skyblocker#998]
### What happened?

Go to auction agent, auction browser, click on item i want to buy, nothing happens.

### Log output

net.minecraft.class_148: Main thread packet handler
	at net.minecraft.class_2600.method_11072(class_2600.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1283) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_7842.method_25355(net.minecraft.class_2561)" because "this.priceWidget" is null
	at de.hysky.skyblocker.skyblock.auction.AuctionViewScreen.getPriceFromTooltip(AuctionViewScreen.java:272) ~[skyblocker-1.20.2+1.20.4.jar:?]
	at de.hysky.skyblocker.skyblock.auction.AuctionViewScreen.onSlotChange(AuctionViewScreen.java:212) ~[skyblocker-1.20.2+1.20.4.jar:?]
	at de.hysky.skyblocker.skyblock.auction.AuctionViewScreen.onSlotChange(AuctionViewScreen.java:30) ~[skyblocker-1.20.2+1.20.4.jar:?]
	at de.hysky.skyblocker.utils.render.gui.AbstractCustomHypixelGUI.method_7635(AbstractCustomHypixelGUI.java:48) ~[skyblocker-1.20.2+1.20.4.jar:?]
	at net.minecraft.class_1703.method_34246(class_1703.java:219) ~[client-intermediary.jar:?]
	at net.minecraft.class_1703.method_7623(class_1703.java:176) ~[client-intermediary.jar:?]
	at net.minecraft.class_1703.method_7596(class_1703.java:139) ~[client-intermediary.jar:?]
	at de.hysky.skyblocker.utils.render.gui.AbstractCustomHypixelGUI.<init>(AbstractCustomHypixelGUI.java:18) ~[skyblocker-1.20.2+1.20.4.jar:?]
	at de.hysky.skyblocker.skyblock.auction.AuctionViewScreen.<init>(AuctionViewScreen.java:50) ~[skyblocker-1.20.2+1.20.4.jar:?]
	at net.minecraft.class_3929$class_3930.handler$bfl000$skyblocker$open(class_3929.java:568) ~[client-intermediary.jar:?]
	at net.minecraft.class_3929$class_3930.method_17543(class_3929.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_3929.method_17541(class_3929.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_17587(class_634.java:1182) ~[client-intermediary.jar:?]
	at net.minecraft.class_3944.method_17591(class_3944.java:37) ~[client-intermediary.jar:?]
	at net.minecraft.class_3944.method_11054(class_3944.java:11) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[client-intermediary.jar:?]
	... 13 more

### Minecraft Version

1.21.0/1.21.1

### Skyblocker Version

skyblocker-1.20.2+1.20.4.jar

### Additional context

It worked perfectly for long time until it decided not to work. Only fix is to disable better auction but not good solution. Also settings in inventory missing. I tried removing config but doesn't fix it either.

**Comment by AzureAaron** [comment]
I believe this issue has since been fixed, update to the latest Skyblocker version.
